// src/modules/list/components/ListHeader.tsx
import { useState } from "react";
import { Trash2, AlertTriangle } from "lucide-react";

interface ListHeaderProps {
  dragHandleProps: any; // vindo do Draggable pai
  listId: string;
  title: string;
  cardCount: number;
  wipLimit?: number;
  accentColor: string;
  onRename: (newTitle: string) => void;
  onDelete: () => void;
}

export function ListHeader({
  dragHandleProps,
  title: initialTitle,
  cardCount,
  wipLimit,
  accentColor,
  onRename,
  onDelete,
}: ListHeaderProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [title, setTitle] = useState(initialTitle);

  const isWipExceeded = wipLimit != null && cardCount >= wipLimit;

  const handleSubmit = () => {
    setIsEditing(false);
    if (title.trim() && title !== initialTitle) {
      onRename(title.trim());
    } else {
      setTitle(initialTitle);
    }
  };

  const handleCancel = () => {
    setTitle(initialTitle);
    setIsEditing(false);
  };

  return (
    <div
      className="px-4 pt-3.5 pb-3 flex items-center justify-between gap-2 cursor-grab active:cursor-grabbing"
      {...dragHandleProps}
    >
      <div className="flex items-center gap-2 flex-1 min-w-0">
        {isEditing ? (
          <input
            autoFocus
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            onBlur={handleSubmit}
            onKeyDown={(e) => {
              if (e.key === "Enter") handleSubmit();
              if (e.key === "Escape") handleCancel();
            }}
            className="font-semibold text-[14px] rounded-lg px-2 py-0.5 focus:outline-none w-full"
            style={{
              background: "var(--app-bg)",
              color: "var(--app-text)",
              border: `1px solid ${accentColor}60`,
            }}
          />
        ) : (
          <h2
            onClick={() => setIsEditing(true)}
            className="font-semibold text-[14px] truncate cursor-text transition-colors"
            style={{ color: "var(--app-text)" }}
          >
            {title}
          </h2>
        )}
      </div>

      <div className="flex items-center gap-2 shrink-0">
        <div
          className="flex items-center gap-1 text-[11px] font-bold px-2 py-0.5 rounded-full"
          style={{
            background: isWipExceeded ? "rgba(248,113,113,0.15)" : "var(--app-hover)",
            color: isWipExceeded ? "#f87171" : "var(--app-text-muted)",
            border: isWipExceeded ? "1px solid rgba(248,113,113,0.3)" : "1px solid transparent",
          }}
        >
          {isWipExceeded && <AlertTriangle className="w-3 h-3" />}
          {cardCount}
          {wipLimit != null && `/${wipLimit}`}
        </div>

        <button
          onClick={(e) => {
            e.stopPropagation();
            onDelete();
          }}
          className="opacity-0 group-hover/list:opacity-100 transition-opacity p-1 rounded-md"
          style={{ color: "var(--app-text-muted)" }}
          onMouseEnter={(e) => (e.currentTarget.style.color = "#f87171")}
          onMouseLeave={(e) => (e.currentTarget.style.color = "var(--app-text-muted)")}
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}

// src/lib/components/column/ListHeader.svelte
<script lang="ts">
  import { Trash2 } from 'lucide-svelte';
  import ListTypePicker from './ListTypePicker.svelte';
  import WipLimitPicker from './WipLimitPicker.svelte';
  import ConfirmationModal from '$lib/ui/ConfirmationModal.svelte';
  import type { ColumnType } from '$lib/contracts/models';

  interface Props {
    title: string;
    cardCount: number;
    wipLimit?: number | null;
    columnType?: ColumnType | null;
    accentColor?: string;
    canEdit?: boolean;
    onrename?: (newTitle: string) => void;
    ondelete?: () => void;
    ontypechange?: (type: ColumnType) => void;
    onwiplimitchange?: (wip: number | null) => void;
  }

  let {
    title,
    cardCount,
    wipLimit = null,
    columnType = 'TODO',
    accentColor = 'var(--app-primary, #818cf8)',
    canEdit = true,
    onrename,
    ondelete,
    ontypechange,
    onwiplimitchange,
  }: Props = $props();

  let isEditing = $state(false);
  let editTitle = $derived(title);
  let isDeleteModalOpen = $state(false);

  function handleSubmit() {
    isEditing = false;
    const trimmed = editTitle.trim();
    if (trimmed && trimmed !== title) {
      onrename?.(trimmed);
    } else {
      editTitle = title;
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') handleSubmit();
    if (e.key === 'Escape') {
      editTitle = title;
      isEditing = false;
    }
  }
</script>

<div class="group flex items-center justify-between gap-2 px-4 pt-3.5 pb-3">
  <div class="flex min-w-0 flex-1 items-center gap-2">
    {#if isEditing}
      <input
        type="text"
        bind:value={editTitle}
        onblur={handleSubmit}
        onkeydown={handleKeyDown}
        class="w-full rounded-lg px-2 py-0.5 text-[14px] font-semibold focus:outline-none"
        style="background: var(--app-bg); color: var(--app-text); border: 1px solid {accentColor}60;"
      />
    {:else}
      <button
        type="button"
        onclick={() => {
          if (canEdit) isEditing = true;
        }}
        class="truncate text-left text-[14px] font-semibold transition-colors {canEdit ? 'cursor-text hover:text-white' : 'cursor-default'}"
        style="color: var(--app-text);"
      >
        {title}
      </button>
    {/if}
  </div>

  <div class="flex shrink-0 items-center gap-2">
    <ListTypePicker
      {columnType}
      {canEdit}
      onchange={ontypechange}
    />

    <WipLimitPicker
      {cardCount}
      {wipLimit}
      {canEdit}
      onchange={onwiplimitchange}
    />

    {#if canEdit}
      <button
        type="button"
        aria-label="Delete list"
        onclick={() => (isDeleteModalOpen = true)}
        class="rounded-md p-1 opacity-0 transition-opacity group-hover:opacity-100"
        style="color: var(--app-text-muted);"
        onmouseenter={(e) => (e.currentTarget.style.color = 'var(--color-danger, #f87171)')}
        onmouseleave={(e) => (e.currentTarget.style.color = 'var(--app-text-muted)')}
      >
        <Trash2 class="h-3.5 w-3.5" />
      </button>
    {/if}
  </div>
</div>

<ConfirmationModal
  isOpen={isDeleteModalOpen}
  onClose={() => (isDeleteModalOpen = false)}
  onConfirm={() => {
    isDeleteModalOpen = false;
    ondelete?.();
  }}
  title="Delete List"
  description="Are you sure you want to delete this list and all its cards? This cannot be undone."
  confirmText="Delete List"
  variant="danger"
/>
