// src/lib/ui/ConfirmationModal.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { AlertTriangle, X, Loader2 } from 'lucide-svelte';
  import { focusTrap } from './focus-trap';

  interface Props {
    isOpen: boolean;
    title: string;
    description: string;
    confirmText?: string;
    cancelText?: string;
    variant?: 'danger' | 'warning' | 'primary';
    loading?: boolean;
    onClose: () => void;
    onConfirm: () => void;
  }

  let {
    isOpen = false,
    title,
    description,
    confirmText = 'Confirm',
    cancelText = 'Cancel',
    variant = 'danger',
    loading = false,
    onClose,
    onConfirm,
  }: Props = $props();

  let dialogEl = $state<HTMLDivElement | null>(null);

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && isOpen && !loading) {
      e.preventDefault();
      onClose();
    }
  }

  onMount(() => {
    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });
</script>

{#if isOpen}
  <div class="modal-root">
    <button
      type="button"
      class="modal-backdrop"
      onclick={onClose}
      aria-label="Close dialog backdrop"
      tabindex="-1"
    ></button>

    <div
      bind:this={dialogEl}
      use:focusTrap
      role="dialog"
      aria-modal="true"
      aria-labelledby="confirm-dialog-title"
      tabindex="-1"
      class="modal-box"
    >
      <div class="modal-header">
        <div class="title-row">
          <span class="icon-wrap icon-{variant}">
            <AlertTriangle size={18} />
          </span>
          <h2 id="confirm-dialog-title" class="title-text">{title}</h2>
        </div>
        <button type="button" class="close-btn" onclick={onClose} disabled={loading} aria-label="Close modal">
          <X size={18} />
        </button>
      </div>

      <div class="modal-body">
        <p class="desc-text">{description}</p>

        <div class="actions-col">
          <button
            type="button"
            class="confirm-btn confirm-{variant}"
            disabled={loading}
            onclick={onConfirm}
          >
            {#if loading}
              <Loader2 size={16} class="spinner" />
              <span>Processing...</span>
            {:else}
              {confirmText}
            {/if}
          </button>

          <button
            type="button"
            class="cancel-btn"
            disabled={loading}
            onclick={onClose}
          >
            {cancelText}
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-root {
    position: fixed;
    inset: 0;
    z-index: var(--z-modal);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1rem;
    animation: fadeIn var(--motion-fast) var(--ease-standard);
  }

  .modal-backdrop {
    position: absolute;
    inset: 0;
    background: var(--overlay-standard);
    backdrop-filter: blur(8px);
    border: none;
    cursor: default;
  }

  .modal-box {
    position: relative;
    z-index: 1;
    width: 100%;
    max-width: 380px;
    background: var(--app-bg);
    border: 1px solid var(--app-border);
    border-radius: var(--radius-control);
    box-shadow: var(--shadow-modal);
    overflow: hidden;
    animation: scaleIn var(--motion-panel) var(--ease-out);
    outline: none;
  }

  .modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.25rem 1.5rem 1rem;
    border-bottom: 1px solid var(--app-border-faint);
  }

  .title-row {
    display: flex;
    align-items: center;
    gap: 0.65rem;
  }

  .title-text {
    margin: 0;
    font-size: 15px;
    font-weight: 700;
    color: var(--app-text);
  }

  .icon-wrap {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .icon-danger { color: var(--color-danger); }
  .icon-warning { color: var(--color-warning); }
  .icon-primary { color: var(--app-primary); }

  .close-btn {
    color: var(--app-text-muted);
    border-radius: var(--radius-micro);
    padding: 4px;
    transition: all var(--motion-fast) var(--ease-standard);
  }
  .close-btn:hover:not(:disabled) {
    background: var(--app-hover);
    color: var(--app-text);
  }

  .modal-body {
    padding: 1.25rem 1.5rem 1.5rem;
  }

  .desc-text {
    margin: 0 0 1.5rem;
    font-size: 13.5px;
    line-height: 1.55;
    color: var(--app-text-muted);
  }

  .actions-col {
    display: flex;
    flex-direction: column;
    gap: 0.65rem;
  }

  .confirm-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.65rem 1rem;
    font-size: 13.5px;
    font-weight: 700;
    border-radius: var(--radius-control);
    border: 1px solid transparent;
    cursor: pointer;
    transition: all var(--motion-fast) var(--ease-standard);
  }

  .confirm-danger {
    background: rgba(239, 68, 68, 0.12);
    border-color: rgba(239, 68, 68, 0.3);
    color: var(--color-danger);
  }
  .confirm-danger:hover:not(:disabled) {
    background: rgba(239, 68, 68, 0.22);
    border-color: rgba(239, 68, 68, 0.5);
  }

  .confirm-warning {
    background: rgba(245, 158, 11, 0.12);
    border-color: rgba(245, 158, 11, 0.3);
    color: var(--color-warning);
  }
  .confirm-warning:hover:not(:disabled) {
    background: rgba(245, 158, 11, 0.22);
  }

  .confirm-primary {
    background: var(--action-primary-solid);
    color: #ffffff;
  }
  .confirm-primary:hover:not(:disabled) {
    background: var(--action-primary-hover);
  }

  .confirm-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .cancel-btn {
    width: 100%;
    padding: 0.65rem 1rem;
    font-size: 13.5px;
    font-weight: 500;
    border-radius: var(--radius-control);
    background: var(--app-panel);
    border: 1px solid var(--app-border-faint);
    color: var(--app-text-muted);
    cursor: pointer;
    transition: all var(--motion-fast) var(--ease-standard);
  }
  .cancel-btn:hover:not(:disabled) {
    background: var(--app-hover);
    color: var(--app-text);
  }

  :global(.spinner) {
    animation: spin 0.6s linear infinite;
  }

  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  @keyframes scaleIn {
    from { opacity: 0; transform: scale(0.96) translateY(8px); }
    to { opacity: 1; transform: scale(1) translateY(0); }
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }
</style>

// src/modules/shared/components/ConfirmationModal.tsx
'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, Loader2, X } from 'lucide-react';

interface ConfirmationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => Promise<void> | void;
  title: string;
  description: string;
  confirmText?: string;
  cancelText?: string;
  variant?: 'danger' | 'warning' | 'primary';
  isLoading?: boolean;
}

export function ConfirmationModal({
  isOpen,
  onClose,
  onConfirm,
  title,
  description,
  confirmText = 'Confirm',
  cancelText = 'Cancel',
  variant = 'danger',
  isLoading = false,
}: ConfirmationModalProps) {
  const variantStyles = {
    danger: {
      button: 'bg-red-500/10 text-red-400 border-red-500/30 hover:bg-red-500/20 hover:border-red-500/50',
      icon: 'text-red-400',
    },
    warning: {
      button: 'bg-amber-500/10 text-amber-400 border-amber-500/30 hover:bg-amber-500/20 hover:border-amber-500/50',
      icon: 'text-amber-400',
    },
    primary: {
      button: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30 hover:bg-indigo-500/20 hover:border-indigo-500/50',
      icon: 'text-indigo-400',
    },
  };

  const currentVariant = variantStyles[variant];

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[999] flex items-center justify-center p-4">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 10 }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            className="relative w-full max-w-[380px] bg-(--app-bg) border border-(--app-border) rounded-sm shadow-[0_32px_80px_rgba(0,0,0,0.6)] flex flex-col overflow-hidden"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 pt-6 pb-5 border-b border-(--app-border-faint)">
              <h2 className="text-md font-bold text-(--app-text) tracking-tight flex items-center gap-3">
                <AlertTriangle className={`w-5 h-5 ${currentVariant.icon}`} />
                {title}
              </h2>
              <button
                onClick={onClose}
                disabled={isLoading}
                className="text-(--app-text-muted) hover:text-(--app-text) transition-colors p-1.5 hover:bg-(--app-panel) rounded-sm disabled:opacity-50"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Body */}
            <div className="px-6 pt-5 pb-6">
              <p className="text-[13.5px] text-(--app-text-muted) mb-6 leading-relaxed opacity-90">
                {description}
              </p>

              {/* Actions */}
              <div className="flex flex-col gap-3">
                <button
                  onClick={onConfirm}
                  disabled={isLoading}
                  className={`flex items-center justify-center gap-2 w-full px-6 py-3 text-[13.5px] font-bold rounded-sm transition-all border ${currentVariant.button} disabled:opacity-60 disabled:cursor-not-allowed`}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Processing...
                    </>
                  ) : (
                    confirmText
                  )}
                </button>
                
                <button
                  onClick={onClose}
                  disabled={isLoading}
                  className="w-full px-6 py-3 rounded-sm text-[13.5px] font-medium transition-all bg-(--app-panel) border border-(--app-border-faint) text-(--app-text-muted) hover:text-(--app-text) disabled:opacity-50"
                >
                  {cancelText}
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
