// src/lib/ui/Select.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ChevronDown, Check, Loader2 } from 'lucide-svelte';

  export interface SelectOption {
    value: string | number;
    label: string;
    icon?: string;
    color?: string;
    description?: string;
    disabled?: boolean;
  }

  interface Props {
    value?: string | number;
    options: SelectOption[];
    placeholder?: string;
    size?: 'sm' | 'md';
    disabled?: boolean;
    loading?: boolean;
    minWidth?: number;
    class?: string;
    triggerClass?: string;
    onchange?: (value: string | number) => void;
  }

  let {
    value = $bindable(''),
    options,
    placeholder = 'Select...',
    size = 'md',
    disabled = false,
    loading = false,
    minWidth,
    class: customClass = '',
    triggerClass = '',
    onchange,
  }: Props = $props();

  let isOpen = $state(false);
  let triggerEl = $state<HTMLButtonElement | null>(null);
  let menuEl = $state<HTMLDivElement | null>(null);
  let focusedIndex = $state(-1);

  let selectedOption = $derived(options.find((o) => o.value === value));

  function toggle() {
    if (disabled || loading) return;
    isOpen = !isOpen;
    if (isOpen) {
      focusedIndex = options.findIndex((o) => o.value === value);
      if (focusedIndex === -1) focusedIndex = 0;
    }
  }

  function selectOption(option: SelectOption) {
    if (option.disabled) return;
    value = option.value;
    isOpen = false;
    onchange?.(option.value);
    triggerEl?.focus();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (!isOpen) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        toggle();
      }
      return;
    }

    switch (e.key) {
      case 'Escape':
        e.preventDefault();
        isOpen = false;
        triggerEl?.focus();
        break;
      case 'ArrowDown':
        e.preventDefault();
        focusedIndex = (focusedIndex + 1) % options.length;
        break;
      case 'ArrowUp':
        e.preventDefault();
        focusedIndex = (focusedIndex - 1 + options.length) % options.length;
        break;
      case 'Home':
        e.preventDefault();
        focusedIndex = 0;
        break;
      case 'End':
        e.preventDefault();
        focusedIndex = options.length - 1;
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (options[focusedIndex] && !options[focusedIndex].disabled) {
          selectOption(options[focusedIndex]);
        }
        break;
    }
  }

  onMount(() => {
    function handleClickOutside(event: MouseEvent) {
      if (triggerEl && !triggerEl.contains(event.target as Node) && menuEl && !menuEl.contains(event.target as Node)) {
        isOpen = false;
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div class="select-container {customClass}">
  <button
    bind:this={triggerEl}
    type="button"
    aria-haspopup="listbox"
    aria-expanded={isOpen}
    {disabled}
    onclick={toggle}
    onkeydown={handleKeydown}
    class="select-trigger select-{size} {triggerClass}"
    class:is-open={isOpen}
  >
    <div class="trigger-content">
      {#if selectedOption?.icon}
        <span class="trigger-icon" style={selectedOption.color ? `color: ${selectedOption.color};` : ''}>
          {selectedOption.icon}
        </span>
      {/if}
      <span class="trigger-label">
        {selectedOption ? selectedOption.label : placeholder}
      </span>
    </div>

    {#if loading}
      <Loader2 size={size === 'sm' ? 12 : 14} class="spinner" />
    {:else}
      <ChevronDown size={size === 'sm' ? 14 : 16} class="chevron {isOpen ? 'rotate' : ''}" />
    {/if}
  </button>

  {#if isOpen}
    <div
      bind:this={menuEl}
      role="listbox"
      tabindex="-1"
      class="select-dropdown"
      style={minWidth ? `min-width: ${minWidth}px;` : ''}
    >
      <div class="dropdown-list">
        {#each options as option, i (option.value)}
          <button
            type="button"
            role="option"
            aria-selected={option.value === value}
            disabled={option.disabled}
            class="select-item"
            class:is-selected={option.value === value}
            class:is-focused={focusedIndex === i}
            onclick={() => selectOption(option)}
          >
            <div class="item-content">
              {#if option.icon}
                <span class="item-icon" style={option.color ? `color: ${option.color};` : ''}>
                  {option.icon}
                </span>
              {/if}
              <div class="item-text">
                <span class="item-label">{option.label}</span>
                {#if option.description}
                  <span class="item-desc">{option.description}</span>
                {/if}
              </div>
            </div>
            {#if option.value === value}
              <Check size={14} class="check-icon" />
            {/if}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .select-container {
    position: relative;
    display: inline-block;
    width: 100%;
  }

  .select-trigger {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    width: 100%;
    background: var(--app-panel);
    border: 1px solid var(--app-border-faint);
    border-radius: var(--radius-control);
    color: var(--app-text);
    cursor: pointer;
    transition: all var(--motion-fast) var(--ease-standard);
  }

  .select-trigger:hover:not(:disabled) {
    background: var(--app-hover);
    border-color: var(--app-border);
  }

  .select-trigger:focus-visible {
    border-color: var(--app-primary);
    box-shadow: 0 0 0 3px var(--focus-ring);
    outline: none;
  }

  .select-trigger:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .select-sm {
    padding: 0.25rem 0.5rem;
    font-size: 11px;
    height: 28px;
  }

  .select-md {
    padding: 0.45rem 0.75rem;
    font-size: 13px;
    height: 36px;
  }

  .trigger-content {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  .trigger-icon {
    font-size: 13px;
    display: flex;
    align-items: center;
  }

  .trigger-label {
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  :global(.chevron) {
    transition: transform var(--motion-fast) var(--ease-standard);
    opacity: 0.6;
    flex-shrink: 0;
  }

  :global(.chevron.rotate) {
    transform: rotate(180deg);
  }

  :global(.spinner) {
    animation: spin 0.6s linear infinite;
    color: var(--app-primary);
    flex-shrink: 0;
  }

  .select-dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    right: 0;
    background: var(--app-bg);
    border: 1px solid var(--app-border);
    border-radius: var(--radius-control);
    box-shadow: var(--shadow-popover);
    z-index: var(--z-dropdown);
    overflow: hidden;
    padding: 4px;
    animation: fadeIn var(--motion-fast) var(--ease-standard);
  }

  .dropdown-list {
    max-height: 260px;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .select-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    padding: 6px 10px;
    border-radius: var(--radius-control);
    text-align: left;
    color: var(--app-text-muted);
    font-size: 13px;
    cursor: pointer;
    border: none;
    background: none;
    transition: all var(--motion-fast) var(--ease-standard);
  }

  .select-item:hover, .select-item.is-focused {
    background: var(--app-hover);
    color: var(--app-text);
  }

  .select-item.is-selected {
    background: var(--app-primary-muted);
    color: var(--app-primary);
    font-weight: 600;
  }

  .select-item:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .item-content {
    display: flex;
    align-items: center;
    gap: 8px;
    overflow: hidden;
  }

  .item-icon {
    font-size: 13px;
    flex-shrink: 0;
  }

  .item-text {
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .item-label {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .item-desc {
    font-size: 10px;
    opacity: 0.6;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  :global(.check-icon) {
    color: var(--app-primary);
    flex-shrink: 0;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(-4px); }
    to { opacity: 1; transform: translateY(0); }
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }
</style>

// src/modules/shared/components/Select.tsx
"use client";

import { useState, useRef, useEffect } from "react";
import { ChevronDown, Check, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { createPortal } from "react-dom";

export interface SelectOption {
  value: string | number;
  label: string;
  icon?: React.ReactNode;
  color?: string;
  description?: string;
  disabled?: boolean;
}

interface SelectProps {
  value: string | number;
  onChange: (value: any) => void;
  options: SelectOption[];
  disabled?: boolean;
  className?: string;
  triggerClassName?: string;
  placeholder?: string;
  size?: "sm" | "md";
  minWidth?: number;
  isLoading?: boolean;
}

export function Select({
  value,
  onChange,
  options,
  disabled,
  className = "",
  triggerClassName = "",
  placeholder = "Select...",
  size = "md",
  minWidth,
  isLoading,
}: SelectProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [coords, setCoords] = useState({ top: 0, left: 0, width: 0 });
  const triggerRef = useRef<HTMLButtonElement>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    return () => setMounted(false);
  }, []);

  const selectedOption = options.find((o) => o.value === value);

  const toggle = () => {
    if (disabled) return;
    if (!isOpen && triggerRef.current) {
      const rect = triggerRef.current.getBoundingClientRect();
      setCoords({
        top: rect.bottom + window.scrollY,
        left: rect.left + window.scrollX,
        width: rect.width,
      });
    }
    setIsOpen(!isOpen);
  };

  useEffect(() => {
    const handleScroll = () => {
       if (isOpen && triggerRef.current) {
         const rect = triggerRef.current.getBoundingClientRect();
         setCoords({
           top: rect.bottom + window.scrollY,
           left: rect.left + window.scrollX,
           width: rect.width,
         });
       }
    };
    window.addEventListener("scroll", handleScroll, true);
    return () => window.removeEventListener("scroll", handleScroll, true);
  }, [isOpen]);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (triggerRef.current && !triggerRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    if (isOpen) {
      document.addEventListener("mousedown", handleClickOutside);
    }
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [isOpen]);

  const dropdownContent = (
    <AnimatePresence>
      {isOpen && (
        <motion.div
           initial={{ opacity: 0, y: -4, scale: 0.98 }}
           animate={{ opacity: 1, y: 4, scale: 1 }}
           exit={{ opacity: 0, y: -4, scale: 0.98 }}
           transition={{ duration: 0.15, ease: "easeOut" }}
           style={{
             position: "absolute",
             top: coords.top,
             left: coords.left,
             minWidth: minWidth ?? (size === 'sm' ? Math.max(coords.width, 130) : Math.max(coords.width, 180)),
             zIndex: 9999,
           }}
           className="bg-(--app-bg) border border-(--app-border) rounded-sm shadow-[0_12px_40px_rgba(0,0,0,0.5)] overflow-hidden p-1.5"
        >
          <div className="flex flex-col gap-0.5 max-h-[300px] overflow-y-auto custom-scrollbar">
            {options.map((option) => (
              <button
                key={option.value}
                type="button"
                disabled={option.disabled}
                onClick={() => {
                  if (option.disabled) return;
                  onChange(option.value);
                  setIsOpen(false);
                }}
                className={`flex items-center justify-between w-full rounded-sm text-left transition-all ${
                  size === 'sm' ? 'px-2 py-1.5' : 'px-3 py-2'
                } ${
                  option.disabled 
                    ? "opacity-50 cursor-not-allowed grayscale-[0.5]" 
                    : option.value === value 
                    ? "bg-indigo-500/10 text-indigo-400" 
                    : "text-(--app-text-muted) hover:bg-(--app-hover)/40 hover:text-(--app-text)"
                }`}
              >
                <div className="flex items-center gap-2.5">
                  {option.icon && (
                    <span 
                      style={{ color: option.color }} 
                      className="shrink-0"
                    >
                      {option.icon}
                    </span>
                  )}
                  <div className="flex flex-col">
                    <span className={`text-[13px] font-medium ${option.value === value ? 'font-bold' : ''}`}>
                      {option.label}
                    </span>
                    {option.description && (
                      <span className="text-[10px] opacity-60 line-clamp-1 leading-tight mt-0.5">
                        {option.description}
                      </span>
                    )}
                  </div>
                </div>
                {option.value === value && (
                   <Check size={14} className="shrink-0" />
                )}
              </button>
            ))}
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );

  return (
    <div className={`relative inline-block ${className}`}>
      <button
        ref={triggerRef}
        type="button"
        onClick={toggle}
        disabled={disabled || isLoading}
        className={`flex items-center justify-between gap-2 bg-(--app-panel) border border-(--app-border-faint) rounded-sm transition-all focus:outline-none focus:ring-2 focus:ring-indigo-500/20 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-(--app-hover)/20 shadow-sm ${
          size === 'sm' ? 'px-2 py-1 text-[11px]' : 'px-3 py-2 text-[13px]'
        } ${triggerClassName}`}
      >
        <div className="flex items-center gap-2 truncate">
          {selectedOption?.icon && (
            <span style={{ color: selectedOption.color }} className="shrink-0 scale-90">
              {selectedOption.icon}
            </span>
          )}
          <span className={`truncate font-semibold tracking-tight uppercase text-[10px] ${isLoading ? 'animate-pulse' : ''}`}>
            {selectedOption ? selectedOption.label : placeholder}
          </span>
        </div>
        {isLoading ? (
          <Loader2 size={size === 'sm' ? 12 : 14} className="shrink-0 animate-spin text-indigo-400" />
        ) : (
          <ChevronDown 
            size={size === 'sm' ? 14 : 16} 
            className={`shrink-0 transition-transform duration-300 opacity-60 ${isOpen ? "rotate-180" : ""}`}
          />
        )}
      </button>
      {mounted && createPortal(dropdownContent, document.body)}
    </div>
  );
}
