// src/lib/components/column/ListAddCard.svelte
<script lang="ts">
  import { Plus } from 'lucide-svelte';

  interface Props {
    accentColor?: string;
    onadd?: (content: string) => void;
  }

  let {
    accentColor = 'var(--app-primary, #818cf8)',
    onadd,
  }: Props = $props();

  let isAdding = $state(false);
  let content = $state('');

  function handleSubmit() {
    const trimmed = content.trim();
    if (!trimmed) {
      isAdding = false;
      return;
    }
    onadd?.(trimmed);
    content = '';
    isAdding = false;
  }

  function handleCancel() {
    content = '';
    isAdding = false;
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
    if (e.key === 'Escape') {
      handleCancel();
    }
  }
</script>

<div class="px-3 pb-2">
  {#if isAdding}
    <div class="mt-1 rounded-lg px-2 py-1">
      <textarea
        bind:value={content}
        onkeydown={handleKeyDown}
        placeholder="Descreva a tarefa..."
        rows={2}
        class="w-full resize-none bg-transparent text-[13px] placeholder:opacity-50 focus:outline-none"
        style="color: var(--app-text);"
      ></textarea>

      <div class="flex items-center gap-2 pt-1">
        <button
          type="button"
          onclick={handleSubmit}
          class="flex items-center gap-1 rounded-md px-2.5 py-1.5 text-[12px] font-medium transition-colors"
          style="background: {accentColor}20; color: {accentColor};"
        >
          Add
        </button>

        <button
          type="button"
          onclick={handleCancel}
          class="px-2 py-1 text-[12px] opacity-60 transition-opacity hover:opacity-100"
          style="color: var(--app-text-muted);"
        >
          Cancel
        </button>
      </div>
    </div>
  {:else}
    <button
      type="button"
      onclick={() => (isAdding = true)}
      class="group flex w-full items-center gap-2 py-2 text-[13px] transition-colors"
      style="color: var(--app-text-muted);"
    >
      <Plus class="h-4 w-4 opacity-70 transition-opacity group-hover:opacity-100" />
      <span class="transition-transform group-hover:translate-x-0.5">
        Adicionar tarefa
      </span>
    </button>
  {/if}
</div>

// src/modules/list/components/ListAddCard.tsx
import { useState } from "react";
import { Plus } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface ListAddCardProps {
  accentColor: string;
  onAdd: (content: string) => Promise<any> | void;
}

export function ListAddCard({ accentColor, onAdd }: ListAddCardProps) {
  const [isAdding, setIsAdding] = useState(false);
  const [content, setContent] = useState("");
  const handleSubmit = () => {
    if (!content.trim()) return setIsAdding(false);

    onAdd(content);
    setContent("");
    setIsAdding(false);
  };

  const handleCancel = () => {
    setContent("");
    setIsAdding(false);
  };

  return (
    <div className="px-3 pb-2">
      <AnimatePresence mode="wait">
        {isAdding ? (
          <motion.div
            key="input"
            initial={{ opacity: 0, y: -4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            className="mt-1 px-2 py-1 rounded-lg transition"
            style={{
              background: "transparent",
            }}
          >
            <textarea
              autoFocus
              placeholder="Descreva a tarefa..."
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={2}
              className="w-full bg-transparent resize-none text-[13px] focus:outline-none placeholder:opacity-50"
              style={{ color: "var(--app-text)" }}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSubmit();
                }
                if (e.key === "Escape") handleCancel();
              }}
            />

            <div className="flex items-center gap-2">
              <button
                onClick={handleSubmit}
                className="flex items-center gap-1 text-[12px] font-medium px-2.5 py-1.5 rounded-md transition"
                style={{
                  background: accentColor + "20",
                  color: accentColor,
                }}
              >
                Add
              </button>

              <button
                onClick={handleCancel}
                className="text-[12px] px-2 py-1 opacity-60 hover:opacity-100 transition"
              >
                Cancel
              </button>
            </div>
          </motion.div>
        ) : (
          <motion.button
            key="button"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setIsAdding(true)}
            className="flex items-center gap-2 w-full py-2 text-[13px] transition group"
            style={{ color: "var(--app-text-muted)" }}
          >
            <Plus className="w-4 h-4 opacity-70 group-hover:opacity-100 transition" />
            <span className="group-hover:translate-x-[2px] transition">
              Adicionar tarefa
            </span>
          </motion.button>
        )}
      </AnimatePresence>
    </div>
  );
}
