// src/lib/components/BoardFiltersBar.svelte
<script lang="ts">
  import { X } from 'lucide-svelte';
  import SearchFilter from './SearchFilter.svelte';
  import MemberFilters from './MemberFilters.svelte';
  import PriorityFilters from './PriorityFilters.svelte';
  import LabelFilters from './LabelFilters.svelte';
  import type { UserModel, TagModel, PriorityModel } from '$lib/contracts/models';

  interface Props {
    searchQuery?: string;
    selectedUserFilters?: string[];
    priorityFilter?: string | null;
    labelFilter?: string | null;
    allUsers?: UserModel[];
    tags?: TagModel[];
    priorities?: PriorityModel[];
    onclear?: () => void;
  }

  let {
    searchQuery = $bindable(''),
    selectedUserFilters = $bindable([]),
    priorityFilter = $bindable(null),
    labelFilter = $bindable(null),
    allUsers = [],
    tags = [],
    priorities = [],
    onclear,
  }: Props = $props();

  let hasActiveFilters = $derived(
    searchQuery.trim().length > 0 ||
    selectedUserFilters.length > 0 ||
    priorityFilter !== null ||
    labelFilter !== null
  );

  function clearAllFilters() {
    searchQuery = '';
    selectedUserFilters = [];
    priorityFilter = null;
    labelFilter = null;
    onclear?.();
  }
</script>

<div class="no-scrollbar bg-app-bg border-app-border-faint flex shrink-0 overflow-x-auto border-b px-6">
  <div class="flex w-full items-center gap-6 py-2 text-[13px] font-medium">
    <SearchFilter bind:searchQuery />

    <div class="bg-app-border-faint h-4 w-px shrink-0"></div>

    <MemberFilters bind:selectedUserFilters {allUsers} />

    <div class="bg-app-border-faint h-4 w-px shrink-0"></div>

    <PriorityFilters bind:priorityFilter {priorities} />

    <LabelFilters bind:labelFilter {tags} />

    {#if hasActiveFilters}
      <button
        type="button"
        onclick={clearAllFilters}
        class="clear-filters-btn ml-auto flex shrink-0 items-center gap-1.5 rounded-sm px-2.5 py-1 text-[10px] font-bold tracking-wider uppercase transition-all"
        style="
          color: var(--color-danger, #f87171);
          background: rgba(248, 113, 113, 0.08);
          border: 1px solid rgba(248, 113, 113, 0.2);
        "
      >
        Limpar filtros
        <X class="h-3 w-3" />
      </button>
    {/if}
  </div>
</div>

<style>
  .no-scrollbar::-webkit-scrollbar {
    display: none;
  }
  .no-scrollbar {
    -ms-overflow-style: none;
    scrollbar-width: none;
  }
  .clear-filters-btn:hover {
    background: rgba(248, 113, 113, 0.15) !important;
    transform: translateY(-1px);
  }
</style>

// src/modules/board/components/BoardFiltersBar.tsx
// modules/board/components/BoardFiltersBar.tsx
import { Search, Flag, Tag } from "lucide-react";

interface BoardFiltersBarProps {
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedUserFilters: string[];
  setSelectedUserFilters: (filters: string[]) => void;
  priorityFilter: string | null;
  setPriorityFilter: (filter: string | null) => void;
  labelFilter: string | null;
  setLabelFilter: (filter: string | null) => void;
  allUsers: any[];
  tags: any[];
  priorities: any[];
  hasActiveFilters: boolean;
  clearFilters: () => void;
}

export function BoardFiltersBar({
  searchQuery,
  setSearchQuery,
  selectedUserFilters,
  setSelectedUserFilters,
  priorityFilter,
  setPriorityFilter,
  labelFilter,
  setLabelFilter,
  allUsers,
  tags,
  priorities,
  hasActiveFilters,
  clearFilters,
}: BoardFiltersBarProps) {
  return (
    <div
      className="px-5 shrink-0 sticky z-10 flex overflow-x-auto no-scrollbar"
      style={{
        top: "57px",
        background: "var(--app-header)",
        borderBottom: "1px solid var(--app-border-faint)",
      }}
    >
      <div className="flex items-center gap-4 text-[13px] font-medium w-full py-1">
        {/* Search input */}
        <div className="relative group">
          <Search
            className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 transition-colors"
            style={{
              color: searchQuery
                ? "var(--app-primary)"
                : "var(--app-text-muted)",
            }}
          />
          <input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            type="text"
            placeholder="Search"
            className="rounded-xl py-1.5 pl-9 pr-4 text-sm focus:outline-none w-35 sm:w-50 transition-all"
            style={{
              background: "var(--app-bg)",
              border: `1px solid ${searchQuery ? "var(--app-primary)" : "var(--app-border)"}`,
              color: "var(--app-text)",
            }}
          />
        </div>

        <div
          style={{
            width: "1px",
            height: "18px",
            background: "var(--app-border-faint)",
            flexShrink: 0,
          }}
        />

        {/* Member filters */}
        <div className="flex items-center gap-2 py-2 shrink-0">
          <span
            className="text-[10px] uppercase tracking-widest font-bold"
            style={{ color: "var(--app-text-muted)", opacity: 0.5 }}
          >
            Members
          </span>
          <div className="flex -space-x-1.5">
            {allUsers.map((user) => {
              const isActive = selectedUserFilters.includes(user.id);
              return (
                <button
                  key={user.id}
                  onClick={() =>
                    setSelectedUserFilters(
                      isActive
                        ? selectedUserFilters.filter((id) => id !== user.id)
                        : [...selectedUserFilters, user.id]
                    )
                  }
                  className="relative rounded-full transition-all duration-200"
                  style={{
                    zIndex: isActive ? 20 : 10,
                    transform: isActive ? "scale(1.12)" : "scale(1)",
                    outline: isActive
                      ? `2px solid var(--app-primary)`
                      : "none",
                    outlineOffset: "1px",
                  }}
                  title={user.display_name || user.username}
                >
                  <img
                    src={
                      user.avatar_url ||
                      `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.username}`
                    }
                    className="w-6 h-6 rounded-full object-cover"
                    style={{
                      border: "2px solid var(--app-header)",
                      opacity: isActive ? 1 : 0.65,
                    }}
                  />
                  {isActive && (
                    <div
                      className="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 rounded-full border-2"
                      style={{
                        background: "var(--app-primary)",
                        borderColor: "var(--app-header)",
                      }}
                    />
                  )}
                </button>
              );
            })}
          </div>
        </div>

        <div
          style={{
            width: "1px",
            height: "18px",
            background: "var(--app-border-faint)",
            flexShrink: 0,
          }}
        />

        {/* Priority filter */}
        <div className="flex items-center gap-1.5 py-2 shrink-0">
          <Flag
            className="w-3 h-3"
            style={{ color: "var(--app-text-muted)", opacity: 0.5 }}
          />
          {priorities.map((p) => (
            <button
              key={p.id}
              onClick={() =>
                setPriorityFilter(priorityFilter === p.name ? null : p.name)
              }
              className="text-[10px] font-bold px-2 py-0.5 rounded-full transition-all"
              style={{
                background:
                  priorityFilter === p.name ? p.color + "25" : "transparent",
                color:
                  priorityFilter === p.name ? p.color : "var(--app-text-muted)",
                border: `1px solid ${priorityFilter === p.name ? p.color + "50" : "transparent"}`,
              }}
            >
              {p.icon} {p.name}
            </button>
          ))}
        </div>

        {/* Label filter */}
        <div className="flex items-center gap-1.5 py-2 shrink-0">
          <Tag
            className="w-3 h-3"
            style={{ color: "var(--app-text-muted)", opacity: 0.5 }}
          />
          {tags.map((l) => (
            <button
              key={l.id}
              onClick={() => setLabelFilter(labelFilter === l.name ? null : l.name)}
              className="text-[10px] font-bold px-2 py-0.5 rounded-full transition-all"
              style={{
                background:
                  labelFilter === l.name ? l.color + "25" : "transparent",
                color:
                  labelFilter === l.name ? l.color : "var(--app-text-muted)",
                border: `1px solid ${labelFilter === l.name ? l.color + "50" : "transparent"}`,
              }}
            >
              {l.name}
            </button>
          ))}
        </div>

        {hasActiveFilters && (
          <button
            onClick={clearFilters}
            className="ml-auto text-[11px] font-bold uppercase tracking-wider transition-colors shrink-0 px-2 py-1 rounded-lg"
            style={{ color: "var(--app-text-muted)" }}
            onMouseEnter={(e) => (e.currentTarget.style.color = "#f87171")}
            onMouseLeave={(e) =>
              (e.currentTarget.style.color = "var(--app-text-muted)")
            }
          >
            Limpar filtros ✕
          </button>
        )}
      </div>
    </div>
  );
}
