// src/lib/components/BoardCanvas.svelte
<script lang="ts">
  import { Plus } from 'lucide-svelte';
  import BoardColumn from './column/BoardColumn.svelte';
  import type { ColumnModel, IssueModel, PriorityModel, TagModel, UserModel, ColumnType } from '$lib/contracts/models';
  import { canMoveIssueToColumn } from '$lib/utils/dnd';
  import { showToast } from '$lib/ui/toast';

  interface Props {
    columns: ColumnModel[];
    priorities?: PriorityModel[];
    tags?: TagModel[];
    allUsers?: UserModel[];
    canWrite?: boolean;
    recentlyCreatedIssueId?: string | null;
    oncardclick?: (card: IssueModel) => void;
    oncarddelete?: (cardId: string) => void;
    onaddcard?: (columnId: string, content: string) => void;
    onaddcolumn?: (title: string) => void;
    ondeletecolumn?: (columnId: string) => void;
    onrenamecolumn?: (columnId: string, newTitle: string) => void;
    ontypechange?: (columnId: string, type: ColumnType) => void;
    onwiplimitchange?: (columnId: string, wip: number | null) => void;
    onmoveissue?: (issueId: string, targetColumnId: string, targetIndex: number) => void;
  }

  let {
    columns = [],
    priorities = [],
    tags = [],
    allUsers = [],
    canWrite = true,
    recentlyCreatedIssueId = null,
    oncardclick,
    oncarddelete,
    onaddcard,
    onaddcolumn,
    ondeletecolumn,
    onrenamecolumn,
    ontypechange,
    onwiplimitchange,
    onmoveissue,
  }: Props = $props();

  let isAddingList = $state(false);
  let newListTitle = $state('');

  let draggedCard = $state<IssueModel | null>(null);
  let dragOverColumnId = $state<string | null>(null);

  function handleCreateList() {
    const trimmed = newListTitle.trim();
    if (!trimmed) {
      isAddingList = false;
      return;
    }
    onaddcolumn?.(trimmed);
    newListTitle = '';
    isAddingList = false;
  }

  function handleCardDragStart(e: DragEvent, card: IssueModel) {
    if (!canWrite) return;
    draggedCard = card;
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = 'move';
      e.dataTransfer.setData('text/plain', card.id);
    }
  }

  function handleCardDragEnd() {
    draggedCard = null;
    dragOverColumnId = null;
  }

  function handleColumnDragOver(e: DragEvent, columnId: string) {
    if (!draggedCard || !canWrite) return;
    dragOverColumnId = columnId;
  }

  function handleColumnDragLeave(e: DragEvent, columnId: string) {
    if (dragOverColumnId === columnId) {
      dragOverColumnId = null;
    }
  }

  function handleColumnDrop(e: DragEvent, targetColumnId: string) {
    if (!draggedCard || !canWrite) return;

    const sourceCol = columns.find((c) => c.issues.some((i) => i.id === draggedCard?.id));
    const targetCol = columns.find((c) => c.id === targetColumnId);

    if (sourceCol && targetCol) {
      const check = canMoveIssueToColumn(draggedCard, targetCol, sourceCol);
      if (!check.allowed) {
        showToast(check.reason ?? 'Não foi possível mover a tarefa para esta lista.', 'error');
        handleCardDragEnd();
        return;
      }

      const targetIndex = targetCol.issues.length;
      onmoveissue?.(draggedCard.id, targetColumnId, targetIndex);
    }

    handleCardDragEnd();
  }
</script>

<div class="board-canvas custom-scrollbar flex w-full flex-1 items-start gap-4 overflow-x-auto p-5 md:p-6">
  {#each columns as column (column.id)}
    <BoardColumn
      {column}
      {priorities}
      {tags}
      {allUsers}
      {canWrite}
      {recentlyCreatedIssueId}
      isDraggingOver={dragOverColumnId === column.id}
      draggedIssueId={draggedCard?.id ?? null}
      {oncardclick}
      {oncarddelete}
      {onaddcard}
      {ondeletecolumn}
      {onrenamecolumn}
      {ontypechange}
      {onwiplimitchange}
      ondragover={handleColumnDragOver}
      ondragleave={handleColumnDragLeave}
      ondrop={handleColumnDrop}
      oncarddragstart={handleCardDragStart}
      oncarddragend={handleCardDragEnd}
    />
  {/each}

  {#if canWrite}
    <div class="min-w-[260px] shrink-0">
      {#if isAddingList}
        <div
          class="rounded-[18px] p-3"
          style="
            background: var(--app-panel, #212124);
            border: 1px solid var(--app-border, rgba(255, 255, 255, 0.1));
          "
        >
          <input
            type="text"
              placeholder="Título da lista"
            bind:value={newListTitle}
            onkeydown={(e) => {
              if (e.key === 'Enter') handleCreateList();
              if (e.key === 'Escape') isAddingList = false;
            }}
            class="w-full rounded-xl px-3 py-2 text-[13px] focus:outline-none"
            style="
              background: var(--app-bg, #151515);
              color: var(--app-text, #ffffff);
              border: 1px solid var(--app-border, rgba(255, 255, 255, 0.1));
            "
          />
          <div class="mt-2.5 flex items-center gap-2 pl-1">
            <button
              type="button"
              onclick={handleCreateList}
              class="rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors"
              style="
                background: var(--app-primary-muted, rgba(99, 102, 241, 0.2));
                color: var(--app-primary, #818cf8);
                border: 1px solid var(--app-primary, #818cf8);
              "
            >
              Adicionar
            </button>
            <button
              type="button"
              onclick={() => (isAddingList = false)}
              class="rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors"
              style="color: var(--app-text-muted);"
            >
              Cancelar
            </button>
          </div>
        </div>
      {:else}
        <button
          type="button"
          onclick={() => (isAddingList = true)}
          class="create-list-btn flex w-full items-center justify-center gap-2 rounded-[18px] px-4 py-4 text-sm font-semibold transition-all"
          style="
            color: var(--app-text-muted);
            border: 1.5px dashed var(--app-border, rgba(255, 255, 255, 0.15));
            background: transparent;
          "
        >
          <Plus class="h-4 w-4" /> Criar lista
        </button>
      {/if}
    </div>
  {/if}
</div>

<style>
  .create-list-btn:hover {
    color: var(--app-primary, #818cf8) !important;
    border-color: var(--app-primary, #818cf8) !important;
    background: var(--app-primary-muted, rgba(99, 102, 241, 0.2)) !important;
  }
</style>

// src/modules/board/components/BoardCanvas.tsx

import { useState } from "react";
import { Droppable } from "@hello-pangea/dnd";
import { Plus } from "lucide-react";

import { List as ListType, Card as CardType, ListType as LType } from "@/modules/board/actions/board";
import List from "@/modules/list/components/List";

interface BoardCanvasProps {
  lists: ListType[];
  cards: CardType[];
  onAddCard: (listId: string, content: string) => Promise<any> | void;
  onAddList: (title: string) => Promise<any> | void;
  onDeleteList: (listId: string) => void;
  onDeleteCard: (cardId: string) => void;
  onCardClick: (card: CardType) => void;
  allUsers: any[];
  commentCounts: Record<string, number>;
  userAvatarUrl: string;
  onListTypeChange?: (listId: string, type: LType) => void;
}

const DEFAULT_WIP_LIMIT = 5;

export function BoardCanvas({
  lists,
  cards,
  onAddCard,
  onAddList,
  onDeleteList,
  onDeleteCard,
  onCardClick,
  allUsers,
  commentCounts,
  userAvatarUrl,
  onListTypeChange,
}: BoardCanvasProps) {
  const [isAddingList, setIsAddingList] = useState(false);
  const [newListTitle, setNewListTitle] = useState("");

  const handleCreateList = () => {
    if (!newListTitle.trim()) return setIsAddingList(false);
    
    if (onAddList) {
      onAddList(newListTitle);
    }
    setNewListTitle("");
    setIsAddingList(false);
  };


  return (
    <div className="p-5 md:p-6 flex-1 overflow-x-auto overflow-y-auto w-full flex items-start gap-4">
      <Droppable droppableId="board" type="list" direction="horizontal">
        {(provided) => (
          <div
            ref={provided.innerRef}
            {...provided.droppableProps}
            className="flex items-start gap-4 h-full"
          >
            {lists.map((list, index) => {
              const listCards = cards
                .filter((c) => c.list_id === list.id)
                .sort((a, b) => a.position - b.position);
              return (
                <List
                  key={list.id}
                  list={list}
                  cards={listCards}
                  index={index}
                  totalLists={lists.length}
                  onAddCard={onAddCard}
                  onDeleteList={() => onDeleteList(list.id)}
                  onDeleteCard={onDeleteCard}
                  onCardClick={onCardClick}
                  avatarUrl={userAvatarUrl}
                  allUsers={allUsers}
                  commentCounts={commentCounts}
                  wipLimit={list.wip_limit ?? DEFAULT_WIP_LIMIT}
                  onListTypeChange={onListTypeChange}
                />
              );
            })}
            {provided.placeholder}
          </div>
        )}
      </Droppable>

      {/* Add list button */}
      <div className="min-w-65 shrink-0">
        {isAddingList ? (
          <div
            className="p-3 rounded-[18px]"
            style={{
              background: "var(--app-panel)",
              border: "1px solid var(--app-border)",
            }}
          >
            <input
              autoFocus
              className="w-full px-3 py-2 rounded-xl text-[13px] focus:outline-none"
              style={{
                background: "var(--app-bg)",
                color: "var(--app-text)",
                border: "1px solid var(--app-border)",
              }}
              placeholder="Title"
              value={newListTitle}
              onChange={(e) => setNewListTitle(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleCreateList();
                if (e.key === "Escape") setIsAddingList(false);
              }}
            />
            <div className="flex items-center gap-2 mt-2.5 pl-1">
              <button
                onClick={handleCreateList}
                className="px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors"
                style={{
                  background: "var(--app-primary-muted)",
                  color: "var(--app-primary)",
                  border: "1px solid var(--app-primary)",
                }}
              >
                Add
              </button>
              <button
                onClick={() => setIsAddingList(false)}
                className="px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors"
                style={{ color: "var(--app-text-muted)" }}
              >
                Discard
              </button>
            </div>
          </div>
        ) : (
          <button
            onClick={() => setIsAddingList(true)}
            className="flex items-center justify-center gap-2 w-full py-4 px-4 rounded-[18px] text-sm font-semibold transition-all"
            style={{
              color: "var(--app-text-muted)",
              border: "1.5px dashed var(--app-border)",
              background: "transparent",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.color = "var(--app-primary)";
              e.currentTarget.style.borderColor = "var(--app-primary)";
              e.currentTarget.style.background = "var(--app-primary-muted)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.color = "var(--app-text-muted)";
              e.currentTarget.style.borderColor = "var(--app-border)";
              e.currentTarget.style.background = "transparent";
            }}
          >
            <Plus className="w-4 h-4" /> Create list
          </button>
        )}
      </div>
    </div>
  );
}
