// src/lib/components/LabelFilters.svelte
<script lang="ts">
  import { Tag } from 'lucide-svelte';
  import type { TagModel } from '$lib/contracts/models';

  interface Props {
    tags?: TagModel[];
    labelFilter?: string | null;
    onchange?: (filter: string | null) => void;
  }

  let {
    tags = [],
    labelFilter = $bindable(null),
    onchange,
  }: Props = $props();

  function toggleLabel(name: string) {
    labelFilter = labelFilter === name ? null : name;
    onchange?.(labelFilter);
  }
</script>

<div class="label-filters flex shrink-0 items-center gap-2 py-2">
  <Tag
    class="mr-1 h-3.5 w-3.5"
    style="color: var(--app-text-muted); opacity: 0.4;"
  />
  {#each tags as l (l.id)}
    {@const isSelected = labelFilter === l.name}
    {@const color = l.color || 'var(--app-text)'}
    <button
      type="button"
      onclick={() => toggleLabel(l.name)}
      class="rounded-sm px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase transition-all"
      style="
        background: {isSelected ? `${color}15` : 'transparent'};
        color: {isSelected ? color : 'var(--app-text-muted)'};
        border: 1px solid {isSelected ? `${color}30` : 'transparent'};
        opacity: {labelFilter && !isSelected ? 0.4 : 1};
      "
    >
      {l.name}
    </button>
  {/each}
</div>

// src/modules/board/components/LabelFilters.tsx
import { Tag } from "lucide-react";

interface LabelFiltersProps {
  tags: any[];
  labelFilter: string | null;
  setLabelFilter: (filter: string | null) => void;
}

export function LabelFilters({
  tags,
  labelFilter,
  setLabelFilter,
}: LabelFiltersProps) {
  return (
    <div className="flex items-center gap-2 py-2 shrink-0">
      <Tag
        className="w-3.5 h-3.5 mr-1"
        style={{ color: "var(--app-text-muted)", opacity: 0.4 }}
      />
      {tags.map((l) => (
        <button
          key={l.id}
          onClick={() => setLabelFilter(labelFilter === l.name ? null : l.name)}
          className="text-[10px] font-bold px-2 py-0.5 rounded-sm transition-all uppercase tracking-wider"
          style={{
            background:
              labelFilter === l.name ? (l.color || "var(--app-text)") + "15" : "transparent",
            color:
              labelFilter === l.name ? (l.color || "var(--app-text)") : "var(--app-text-muted)",
            border: `1px solid ${labelFilter === l.name ? (l.color || "var(--app-text)") + "30" : "transparent"}`,
            opacity: labelFilter && labelFilter !== l.name ? 0.4 : 1
          }}
        >
          {l.name}
        </button>
      ))}
    </div>
  );
}
