// src/features/board/components/card/components/card-modal/CardModal.tsx
"use client";

import {  useEffect, useMemo, useRef } from "react";
import { AnimatePresence, motion } from "framer-motion";
import type { Card as CardType  } from '@/contracts/Board';
import { useCardModal } from "../../hooks/useCardModal";
import { CardModalCover } from "./CardModalCover";
import { CardModalHeader } from "./CardModalHeader";
import { CardModalTabs } from "./CardModalTabs";
import { DescriptionTab } from "./description-tab/DescriptionTab";
import { CommentsTab } from "./comments-tab/CommentsTab";
import { DiagramTab } from "./diagram-tab/DiagramTab";
import { ChecklistProgress } from "./ChecklistProgress";

interface CardModalProps {
  card: CardType | null;
  onClose: () => void;
  onUpdate: (updatedCard: CardType) => void;
  currentUserId?: string;
  currentUserAvatar: string;
  allUsers: any[];
  tags: any[];
  priorities: any[];
  workspaceId: string;
  workspaceName: string;
  listName: string;
  initialTab?: "description" | "comments" | "diagram";
}

// Constantes fora do componente: evitam recriação de objeto a cada render e permitem
// compartilhamento futuro sem mudança de API.
const LABELS = [
  { id: "feature", label: "Feature", color: "#818cf8" },
  { id: "bug", label: "Bug", color: "#f87171" },
  { id: "infra", label: "Infra", color: "#94a3b8" },
  { id: "design", label: "Design", color: "#c084fc" },
  { id: "research", label: "Research", color: "#2dd4bf" },
] as const;

const PRIORITIES = [
  { id: "high", label: "High", color: "#f87171", icon: "↑" },
  { id: "medium", label: "Medium", color: "#fbbf24", icon: "→" },
  { id: "low", label: "Low", color: "#34d399", icon: "↓" },
] as const;

export default function CardModal({
  card,
  onClose,
  onUpdate,
  currentUserId,
  currentUserAvatar,
  allUsers,
  tags,
  priorities,
  workspaceId,
  workspaceName,
  listName,
  initialTab,
}: CardModalProps) {
  const {
    content,
    setContent,
    description,
    setDescription,
    coverUrl,
    dueDate,
    setDueDate,
    selectedLabel,
    selectedPriority,
    assigneeId,
    isEditingTitle,
    setIsEditingTitle,
    isEditingDesc,
    setIsEditingDesc,
    activeTab,
    setActiveTab,
    savedStatus,
    comments,
    loadingComments,
    hasMoreComments,
    isLoadingMore,
    loadMoreComments,
    handlePostComment,
    handleDeleteComment,
    history,
    handleSave,
    toggleAssignee,
    handleLabelSelect,
    handlePrioritySelect,
    handleCoverUpload,
    handleRemoveCover,
    checklistCounts,
    diagramData,
    loadingDiagram,
    isSavingDiagram,
    handleSaveDiagram,
  } = useCardModal(card, onUpdate, tags, priorities, workspaceId, initialTab);

  // Ref para handleSave: o listener de keydown é registrado uma única vez (deps: [onClose])
  // e sempre chama a versão mais recente do save via ref, sem re-registrar o listener.
  const handleSaveRef = useRef(handleSave);
  useEffect(() => { handleSaveRef.current = handleSave; }, [handleSave]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key.toLowerCase() === "s") {
        e.preventDefault();
        handleSaveRef.current();
      }
      if (e.key === "Escape") {
        onClose();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]); // handleSave removido: acessado via ref

  if (!card) return null;

  // Memoizados para evitar recálculo em cada render — dependem de campos específicos
  const currentLabel = useMemo(
    () => LABELS.find((l) => l.id === selectedLabel),
    [selectedLabel]
  );
  const currentPriority = useMemo(
    () => PRIORITIES.find((p) => p.id === selectedPriority),
    [selectedPriority]
  );
  const assignedUser = useMemo(
    () => allUsers.find((u) => u.id === assigneeId),
    [allUsers, assigneeId]
  );

  // AnimatePresence externo removido: o componente retorna null quando !card (acima),
  // então AnimatePresence nunca veria o unmount do filho — a animação de saída era inoperante.
  // Para animar o modal ao fechar, envolva <CardModal> com <AnimatePresence> no pai.
  return (
    <div className="fixed inset-0 z-100 flex items-end justify-center sm:items-center">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0"
        style={{ background: "rgba(0,0,0,0.75)", backdropFilter: "blur(12px)" }}
      />

      <motion.div
        initial={{ opacity: 0, y: 40, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 20, scale: 0.97 }}
        transition={{ type: "spring", damping: 28, stiffness: 320 }}
        className="relative z-10 flex max-h-[92vh] w-full max-w-[95vw] flex-col sm:mx-4 sm:h-[48rem] sm:w-[68rem]"
        style={{
          borderRadius: "6px",
          background: "var(--app-bg)",
          border: "1px solid var(--app-border)",
          boxShadow: "0 32px 80px rgba(0,0,0,0.6)",
        }}
      >
        <CardModalCover
          coverUrl={coverUrl}
          isUploading={false} // TODO: manage upload state
          onUpload={handleCoverUpload}
          onRemove={handleRemoveCover}
        />

        <CardModalHeader
          content={content}
          setContent={setContent}
          isEditingTitle={isEditingTitle}
          setIsEditingTitle={setIsEditingTitle}
          dueDate={dueDate}
          setDueDate={setDueDate}
          selectedLabel={selectedLabel}
          selectedPriority={selectedPriority}
          assigneeId={assigneeId}
          assignedUser={assignedUser}
          currentLabel={currentLabel}
          currentPriority={currentPriority}
          onSave={handleSave}
          onToggleAssignee={toggleAssignee}
          onLabelSelect={handleLabelSelect}
          onPrioritySelect={handlePrioritySelect}
          onCoverUpload={handleCoverUpload}
          onClose={onClose}
          allUsers={allUsers}
          tags={tags}
          priorities={priorities}
          workspaceId={workspaceId}
          workspaceName={workspaceName}
          listName={listName}
        />

        <div
          className="relative flex-1 overflow-y-auto"
          style={{
            scrollbarWidth: "thin",
            scrollbarColor: "var(--app-border) transparent",
          }}
        >
          {/* Sticky Navigation Bar */}
          <div className="bg-app-bg border-app-border-faint sticky top-0 z-30 border-b px-6 pt-1 shadow-sm shadow-black/5">
            <CardModalTabs
              activeTab={activeTab}
              setActiveTab={setActiveTab}
              commentsCount={comments.length}
            />

            <ChecklistProgress
              done={checklistCounts.done}
              total={checklistCounts.total}
            />
          </div>

          <AnimatePresence mode="wait">
            {activeTab === "description" ? (
              <motion.div
                key="description"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="px-6 py-5"
              >
                <DescriptionTab
                  description={description}
                  setDescription={setDescription}
                  isEditing={isEditingDesc}
                  setIsEditing={setIsEditingDesc}
                  savedStatus={savedStatus}
                  history={history}
                  allUsers={allUsers}
                  workspaceId={workspaceId}
                />
              </motion.div>
            ) : activeTab === "comments" ? (
              <motion.div
                key="comments"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="px-6 py-5"
              >
                <CommentsTab
                  comments={comments}
                  loading={loadingComments}
                  hasMore={hasMoreComments}
                  isLoadingMore={isLoadingMore}
                  onLoadMore={loadMoreComments}
                  onPostComment={handlePostComment}
                  onDeleteComment={handleDeleteComment}
                  currentUserId={currentUserId}
                  currentUserAvatar={currentUserAvatar}
                  allUsers={allUsers}
                  workspaceId={workspaceId}
                />
              </motion.div>
            ) : (
              <motion.div
                key="diagram"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="px-6 py-5"
              >
                <DiagramTab
                  initialData={diagramData}
                  onSave={handleSaveDiagram}
                  loading={loadingDiagram}
                  isSaving={isSavingDiagram}
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        <div
          className="flex shrink-0 items-center justify-between px-6 py-3.5"
          style={{ borderTop: "1px solid var(--app-border-faint)" }}
        >
          <div className="flex items-center gap-3">
            <img
              src={currentUserAvatar}
              className="h-6 w-6 rounded-[5px] bg-[var(--app-panel)] object-cover"
              style={{ border: "1.5px solid var(--app-border-faint)" }}
            />
            <span className="text-[12px]" style={{ color: "var(--app-text-muted)", opacity: 0.8 }}>
              You are editing this card
            </span>
          </div>

          {/* Keyboard Legends (Desktop only) */}
          <div className="text-app-text-muted hidden items-center gap-4 text-[10px] font-black tracking-widest uppercase opacity-40 md:flex">
            <div className="flex items-center gap-1.5 transition-opacity hover:opacity-100">
              <kbd className="border-app-border bg-app-panel rounded-xs border px-1.5 py-0.5">ESC</kbd>
              <span>Close</span>
            </div>
            <div className="flex items-center gap-1.5 transition-opacity hover:opacity-100">
              {/* Corrigido: SHIF → SHIFT */}
              <kbd className="border-app-border bg-app-panel rounded-xs border px-1.5 py-0.5">CTRL + SHIFT + S</kbd>
              <span>Save</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="rounded-sm px-4 py-2 text-[13.5px] font-medium text-[var(--app-text-muted)] transition-colors hover:bg-[var(--app-panel)] hover:text-[var(--app-text)] focus:outline-none"
            >
              Close
            </button>
            <button
              onClick={async () => {
                // await garante que o save completa antes de fechar o modal,
                // evitando race condition entre a request e o unmount
                await handleSave();
                onClose();
              }}
              className="flex items-center justify-center gap-2 rounded-sm px-6 py-2 text-[13.5px] font-bold text-white shadow-sm shadow-indigo-950/20 transition-all hover:brightness-110 focus:ring-4 focus:ring-indigo-500/20 focus:outline-none"
              style={{ background: 'linear-gradient(135deg, #4f46e5 0%, #312e81 100%)' }}
            >
              Done
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}

// src/lib/components/card-modal/CardModal.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { focusTrap } from '$lib/ui/focus-trap';
  import type {
    IssueModel,
    UserModel,
    TagModel,
    PriorityModel,
    CommentModel,
    IssueEventModel,
    DiagramElementModel,
  } from '$lib/contracts/models';
  import { toCommentModel, toIssueEventModel, toDiagramElementModel } from '$lib/contracts/mappers';
  import { parseChecklistCounts } from '$lib/utils/markdown';
  import CardModalCover from './CardModalCover.svelte';
  import CardModalHeader from './CardModalHeader.svelte';
  import CardModalTabs, { type ModalTab } from './CardModalTabs.svelte';
  import ChecklistProgress from './ChecklistProgress.svelte';
  import DescriptionTab from './DescriptionTab.svelte';
  import CommentsTab from './CommentsTab.svelte';
  import DiagramTab from './DiagramTab.svelte';

  interface Props {
    card: IssueModel | null;
    boardId: string;
    workspaceId: string;
    workspaceName: string;
    listName: string;
    allUsers?: UserModel[];
    tags?: TagModel[];
    priorities?: PriorityModel[];
    currentUserId?: string;
    currentUserAvatar?: string;
    initialTab?: ModalTab;
    onClose?: () => void;
    onUpdate?: (updatedCard: IssueModel) => Promise<void> | void;
  }

  let {
    card,
    boardId,
    workspaceId,
    workspaceName,
    listName,
    allUsers = [],
    tags = [],
    priorities = [],
    currentUserId,
    currentUserAvatar = 'https://api.dicebear.com/7.x/bottts/svg?seed=levity',
    initialTab = 'description',
    onClose,
    onUpdate,
  }: Props = $props();

  // Local card state
  let content = $state('');
  let description = $state('');
  let coverUrl = $state<string | null>(null);
  let dueDate = $state<string | null>(null);
  let selectedTagId = $state<string | null>(null);
  let selectedPriorityId = $state<string>('');
  let assigneeId = $state<string | null>(null);

  // Tab and UI states
  let activeTab = $state<ModalTab>('description');
  let savedStatus = $state<'idle' | 'saving' | 'saved'>('idle');
  let isUploadingCover = $state(false);

  // Comments state
  let comments = $state<CommentModel[]>([]);
  let loadingComments = $state(false);

  // History state
  let history = $state<IssueEventModel[]>([]);

  // Diagram state
  let diagramElements = $state<DiagramElementModel[]>([]);
  let loadingDiagram = $state(false);
  let isSavingDiagram = $state(false);

  // Synchronize when card prop changes
  $effect(() => {
    if (card) {
      content = card.content || '';
      description = card.description || '';
      coverUrl = card.coverUrl || null;
      dueDate = card.dueDate || null;
      selectedTagId = card.tagId || null;
      selectedPriorityId = card.priorityId || '';
      assigneeId = card.assigneeId || null;
      activeTab = initialTab;
    }
  });

  // Fetch comments, history, and diagram when modal opens
  $effect(() => {
    if (card?.id) {
      fetchComments(card.id);
      fetchHistory(card.id);
      fetchDiagram(card.id);
    }
  });

  const assignedUser = $derived(allUsers.find((u) => u.id === assigneeId) || null);
  const checklistCounts = $derived(parseChecklistCounts(description));

  async function fetchComments(issueId: string) {
    loadingComments = true;
    try {
      const res = await fetch(`/api/issues/${issueId}/comments`);
      if (res.ok) {
        const data = await res.json();
        const rawItems = data.items || data;
        if (Array.isArray(rawItems)) {
          const rootComments = rawItems.map(toCommentModel);
          const replies = await Promise.all(rootComments.map(async (comment) => {
            const repliesResponse = await fetch(`/api/comments/${comment.id}/replies`);
            return repliesResponse.ok ? (await repliesResponse.json()).map(toCommentModel) : [];
          }));
          comments = [...rootComments, ...replies.flat()];
        }
      }
    } catch {
      // Graceful fallback
    } finally {
      loadingComments = false;
    }
  }

  async function fetchHistory(issueId: string) {
    try {
      const res = await fetch(`/api/boards/${boardId}/issues/${issueId}/history`);
      if (res.ok) {
        const data = await res.json();
        if (Array.isArray(data)) {
          history = data.map(toIssueEventModel);
        }
      }
    } catch {
      // Graceful fallback
    }
  }

  async function fetchDiagram(issueId: string) {
    loadingDiagram = true;
    try {
      const res = await fetch(`/api/diagrams/${issueId}`);
      if (res.ok) {
        const data = await res.json();
        if (data && Array.isArray(data.elements)) {
          diagramElements = data.elements.map(toDiagramElementModel);
        }
      }
    } catch {
      // Graceful fallback
    } finally {
      loadingDiagram = false;
    }
  }

  async function handleSave(overrides?: Partial<IssueModel>) {
    if (!card) return;

    savedStatus = 'saving';

    const updated: IssueModel = {
      ...card,
      content: overrides?.content !== undefined ? overrides.content : content,
      description: overrides?.description !== undefined ? overrides.description : description,
      coverUrl: overrides?.coverUrl !== undefined ? overrides.coverUrl : coverUrl,
      dueDate: overrides?.dueDate !== undefined ? overrides.dueDate : dueDate,
      tagId: overrides?.tagId !== undefined ? overrides.tagId : selectedTagId,
      priorityId: overrides?.priorityId !== undefined ? overrides.priorityId : selectedPriorityId,
      assigneeId: overrides?.assigneeId !== undefined ? overrides.assigneeId : assigneeId,
    };

    try {
      const res = await fetch(`/api/boards/${boardId}/issues/${card.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: updated.content,
          description: updated.description,
          cover_url: updated.coverUrl,
          due_date: updated.dueDate,
          tag_id: updated.tagId,
          priority_id: updated.priorityId,
          assignee_id: updated.assigneeId,
        }),
      });

      if (!res.ok) {
        savedStatus = 'idle';
        return;
      }

      await onUpdate?.(updated);
      savedStatus = 'saved';
      setTimeout(() => {
        if (savedStatus === 'saved') savedStatus = 'idle';
      }, 2000);
    } catch {
      savedStatus = 'idle';
    }
  }

  async function handlePostComment(text: string, parentId?: string | null) {
    if (!card) return;
    try {
      const res = await fetch(`/api/issues/${card.id}/comments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: text,
          parent_id: parentId || undefined,
        }),
      });
      if (res.ok) {
        const raw = await res.json();
        const newComment = toCommentModel(raw);
        comments = [...comments, newComment];
      }
    } catch {
      // Error handling
    }
  }

  async function handleDeleteComment(commentId: string) {
    try {
      const res = await fetch(`/api/comments/${commentId}`, { method: 'DELETE' });
      if (res.ok || res.status === 204) {
        comments = comments.filter((c) => c.id !== commentId);
      }
    } catch {
      // Error handling
    }
  }

  async function handleUpdateComment(commentId: string, content: string) {
    const response = await fetch(`/api/comments/${commentId}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content }),
    });
    if (!response.ok) throw new Error('Falha ao atualizar comentário.');
    const updatedComment = toCommentModel(await response.json());
    comments = comments.map((comment) => comment.id === commentId ? updatedComment : comment);
  }

  async function handleSaveDiagram(newElements: DiagramElementModel[]) {
    if (!card) return;
    isSavingDiagram = true;
    try {
      const res = await fetch(`/api/diagrams`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          issue_id: card.id,
          data: {
            elements: newElements.map((el) => ({
              id: el.id,
              type: el.type,
              points: el.points,
              x: el.x,
              y: el.y,
              width: el.width,
              height: el.height,
              color: el.color,
              size: el.size,
            })),
          },
        }),
      });
      if (res.ok) {
        diagramElements = newElements;
      }
    } catch {
      // Error handling
    } finally {
      isSavingDiagram = false;
    }
  }

  async function handleDeleteDiagram() {
    if (!card) return;
    isSavingDiagram = true;
    try {
      const res = await fetch(`/api/diagrams/${card.id}`, { method: 'DELETE' });
      if (!res.ok && res.status !== 204) return;
      diagramElements = [];
    } finally {
      isSavingDiagram = false;
    }
  }

  function handleContentChange(newContent: string) {
    content = newContent;
    handleSave({ content: newContent });
  }

  function handleDescriptionChange(newDesc: string) {
    description = newDesc;
    handleSave({ description: newDesc });
  }

  function handleDueDateSelect(newDate: string | null) {
    dueDate = newDate;
    handleSave({ dueDate: newDate });
  }

  function handlePrioritySelect(newPriorityId: string) {
    selectedPriorityId = newPriorityId;
    handleSave({ priorityId: selectedPriorityId });
  }

  function handleTagSelect(newTagId: string | null) {
    selectedTagId = newTagId === selectedTagId ? null : newTagId;
    handleSave({ tagId: selectedTagId });
  }

  function handleAssigneeSelect(newUserId: string | null) {
    assigneeId = newUserId === assigneeId ? null : newUserId;
    handleSave({ assigneeId });
  }

  function handleCoverUpload(url: string) {
    coverUrl = url;
    handleSave({ coverUrl: url });
  }

  function handleCoverRemove() {
    coverUrl = null;
    handleSave({ coverUrl: null });
  }

  onMount(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key.toLowerCase() === 's') {
        e.preventDefault();
        handleSave();
      }
      if (e.key === 'Escape') {
        onClose?.();
      }
    }

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  });
</script>

{#if card}
  <div class="fixed inset-0 z-100 flex items-end justify-center sm:items-center">
    <!-- Backdrop -->
    <button
      type="button"
      class="absolute inset-0 block h-full w-full cursor-default border-0 p-0"
      style="background: rgba(0,0,0,0.75); backdrop-filter: blur(12px);"
      onclick={onClose}
      aria-label="Close card modal"
      in:fade={{ duration: 160 }}
    ></button>

    <!-- Modal Container -->
    <div
      class="relative z-10 flex max-h-[92vh] w-full max-w-[95vw] flex-col sm:mx-4 sm:h-[48rem] sm:w-[68rem]"
      use:focusTrap
      in:fly={{ y: 18, duration: 220 }}
      role="dialog"
      aria-modal="true"
      aria-label="Detalhes da tarefa"
      style="
        border-radius: 6px;
        background: var(--app-bg);
        border: 1px solid var(--app-border);
        box-shadow: 0 32px 80px rgba(0,0,0,0.6);
      "
    >
      <!-- Cover -->
      <CardModalCover
        {coverUrl}
        isUploading={isUploadingCover}
        onRemove={handleCoverRemove}
      />

      <!-- Header -->
      <CardModalHeader
        {content}
        {dueDate}
        {selectedTagId}
        {selectedPriorityId}
        {assigneeId}
        {assignedUser}
        {workspaceName}
        {listName}
        {allUsers}
        {tags}
        {priorities}
        {workspaceId}
        onupdatecontent={handleContentChange}
        onselectduedate={handleDueDateSelect}
        onselectpriority={handlePrioritySelect}
        onselecttag={handleTagSelect}
        onselectassignee={handleAssigneeSelect}
        onuploadcover={handleCoverUpload}
      />

      <!-- Body / Tabs -->
      <div
        class="relative flex-1 overflow-y-auto"
        style="scrollbar-width: thin; scrollbar-color: var(--app-border) transparent;"
      >
        <!-- Sticky Navigation Bar -->
        <div class="sticky top-0 z-30 border-b border-[var(--app-border-faint)] bg-[var(--app-bg)] px-6 pt-1 shadow-sm shadow-black/5">
          <CardModalTabs
            {activeTab}
            commentsCount={comments.length}
            ontabchange={(tab) => (activeTab = tab)}
          />

          <ChecklistProgress
            done={checklistCounts.done}
            total={checklistCounts.total}
          />
        </div>

        <!-- Tab Content -->
        <div class="px-6 py-5">
          {#if activeTab === 'description'}
            <DescriptionTab
              {description}
              {savedStatus}
              {history}
              {allUsers}
              {workspaceId}
              onupdatedescription={handleDescriptionChange}
            />
          {:else if activeTab === 'comments'}
            <CommentsTab
              {comments}
              loading={loadingComments}
              {allUsers}
              {currentUserId}
              {currentUserAvatar}
              {workspaceId}
              onpostcomment={handlePostComment}
              ondeletecomment={handleDeleteComment}
              onupdatecomment={handleUpdateComment}
            />
          {:else if activeTab === 'diagram'}
            <DiagramTab
              elements={diagramElements}
              loading={loadingDiagram}
              isSaving={isSavingDiagram}
              onSave={handleSaveDiagram}
              onDelete={handleDeleteDiagram}
            />
          {/if}
        </div>
      </div>

      <!-- Footer -->
      <div
        class="flex shrink-0 items-center justify-between px-6 py-3.5"
        style="border-top: 1px solid var(--app-border-faint);"
      >
        <div class="flex items-center gap-3">
          <img
            src={currentUserAvatar}
            alt="Current User"
            class="h-6 w-6 rounded-[5px] bg-[var(--app-panel)] object-cover"
            style="border: 1.5px solid var(--app-border-faint);"
          />
          <span class="text-[12px] opacity-80" style="color: var(--app-text-muted);">
            Você está editando esta tarefa
          </span>
        </div>

        <!-- Keyboard Legends (Desktop only) -->
        <div class="hidden items-center gap-4 text-[10px] font-black uppercase tracking-widest opacity-40 md:flex" style="color: var(--app-text-muted);">
          <div class="flex items-center gap-1.5 transition-opacity hover:opacity-100">
            <kbd class="rounded-xs border border-[var(--app-border)] bg-[var(--app-panel)] px-1.5 py-0.5">ESC</kbd>
            <span>Fechar</span>
          </div>
          <div class="flex items-center gap-1.5 transition-opacity hover:opacity-100">
            <kbd class="rounded-xs border border-[var(--app-border)] bg-[var(--app-panel)] px-1.5 py-0.5">CTRL + SHIFT + S</kbd>
            <span>Salvar</span>
          </div>
        </div>

        <div class="flex items-center gap-2">
          <button
            type="button"
            onclick={onClose}
            class="rounded-sm px-4 py-2 text-[13.5px] font-medium text-[var(--app-text-muted)] transition-colors hover:bg-[var(--app-panel)] hover:text-[var(--app-text)] focus:outline-none"
          >
            Fechar
          </button>
          <button
            type="button"
            onclick={async () => {
              await handleSave();
              onClose?.();
            }}
            class="flex items-center justify-center gap-2 rounded-sm px-6 py-2 text-[13.5px] font-bold text-white shadow-sm shadow-indigo-950/20 transition-all hover:brightness-110 focus:ring-4 focus:ring-indigo-500/20 focus:outline-none"
            style="background: linear-gradient(135deg, var(--action-emphasis-start) 0%, var(--action-emphasis-end) 100%);"
          >
            Salvar
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}
