// src/modules/card/components/card-modal/description-tab/HistorySection.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Clock, ChevronDown, ArrowRight } from "lucide-react";
import { timeAgo } from "@/modules/shared/utils/date";
import { ACTION_META, ActionPill } from "../../../utils/historyUtils";

interface HistorySectionProps {
  history: any[];
  allUsers: any[];
}

export function HistorySection({ history, allUsers }: HistorySectionProps) {
  const [isOpen, setIsOpen] = useState(false);
  const sortedHistory = [...history].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );

  return (
    <div className="rounded-sm overflow-hidden" style={{ border: "1px solid var(--app-border-faint)" }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between px-4 py-3 transition-colors group"
        style={{ background: "var(--app-hover)" }}
        onMouseEnter={(e) => (e.currentTarget.style.background = "var(--app-border-faint)")}
        onMouseLeave={(e) => (e.currentTarget.style.background = "var(--app-hover)")}
      >
        <div className="flex items-center gap-2.5">
          <Clock className="w-3.5 h-3.5" style={{ color: "var(--app-text-muted)" }} />
          <span className="text-[13px] font-semibold transition-colors" style={{ color: "var(--app-text-muted)" }}>
            Edit History
          </span>
          {history.length > 0 && (
            <span
              className="px-1.5 py-0.5 rounded-sm text-[10px] font-bold"
              style={{
                background: "var(--app-border)",
                color: "var(--app-text-muted)",
              }}
            >
              {history.length}
            </span>
          )}
        </div>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="w-4 h-4" style={{ color: "var(--app-text-muted)" }} />
        </motion.div>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22, ease: [0.4, 0, 0.2, 1] }}
            style={{
              overflow: "hidden",
              borderTop: "1px solid var(--app-border-faint)",
            }}
          >
            <div className="px-4 pb-4 pt-3">
              {sortedHistory.length === 0 ? (
                <p className="text-[12px] py-3 text-center italic" style={{ color: "var(--app-text-muted)" }}>
                  No edit history recorded.
                </p>
              ) : (
                <ol className="relative pl-8 space-y-0 mt-1">
                  <div
                    className="absolute left-2.75 top-2 bottom-2 w-px"
                    style={{ background: "var(--app-border)" }}
                  />
                  {sortedHistory.map((item, i) => {
                    const user = allUsers.find((u) => u.id === item.createdBy) || item.users;
                    const meta = ACTION_META[item.actionType];
                    return (
                      <motion.li
                        key={item.id}
                        initial={{ opacity: 0, x: -4 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.025 }}
                        className="relative pb-4 last:pb-0"
                      >
                        <span className="absolute -left-8 top-1.25 w-5.5 flex justify-center">
                          <span
                            className="w-2 h-2 rounded-sm shrink-0"
                            style={{
                              background: meta?.dot ?? "#666",
                              boxShadow: `0 0 0 3px var(--app-elevated)`,
                            }}
                          />
                        </span>
                        <div className="flex items-start gap-2 flex-wrap">
                          {user && (
                            <img
                              src={
                                user.avatarUrl ||
                                `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.username}`
                              }
                              className="w-5 h-5 rounded-sm object-cover shrink-0 mt-0.5 bg-[var(--app-panel)]"
                              style={{ border: "1px solid var(--app-border-faint)" }}
                            />
                          )}
                          <span className="text-[12.5px] font-semibold" style={{ color: "var(--app-text-muted)" }}>
                            {user?.displayName || user?.username || "Someone"}
                          </span>
                          <ActionPill type={item.actionType} field={item.field} />
                          {item.actionType === "updated" && item.oldValue && item.newValue && (
                            <span
                              className="flex items-center gap-1 text-[11px] mt-0.5"
                              style={{ color: "var(--app-text-muted)" }}
                            >
                              <span className="line-through truncate max-w-18">{item.oldValue}</span>
                              <ArrowRight className="w-2.5 h-2.5 shrink-0" />
                              <span className="truncate max-w-18">{item.newValue}</span>
                            </span>
                          )}
                        </div>
                        <span className="text-[11px] mt-0.5 block" style={{ color: "var(--app-text-muted)", opacity: 0.6 }}>
                          {timeAgo(item.createdAt)}
                        </span>
                      </motion.li>
                    );
                  })}
                </ol>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// src/lib/components/card-modal/HistorySection.svelte
<script lang="ts">
  import { Clock, ChevronDown } from 'lucide-svelte';
  import type { IssueEventModel, UserModel } from '$lib/contracts/models';

  interface Props {
    history?: IssueEventModel[];
    allUsers?: UserModel[];
  }

  let { history = [], allUsers = [] }: Props = $props();

  let isOpen = $state(false);

  const sortedHistory = $derived(
    [...history].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
  );

  function getUser(userId: string) {
    return allUsers.find((u) => u.id === userId);
  }

  function formatTimeAgo(dateStr: string): string {
    try {
      const date = new Date(dateStr);
      const diffMs = Date.now() - date.getTime();
      const diffMins = Math.floor(diffMs / (1000 * 60));
      if (diffMins < 1) return 'agora';
      if (diffMins < 60) return `${diffMins}m atrás`;
      const diffHours = Math.floor(diffMins / 60);
      if (diffHours < 24) return `${diffHours}h atrás`;
      const diffDays = Math.floor(diffHours / 24);
      return `${diffDays}d atrás`;
    } catch {
      return dateStr;
    }
  }

  function formatAction(item: IssueEventModel): string {
    const field = item.field || 'issue';
    if (item.actionType === 'CREATE') return 'criou esta issue';
    if (item.actionType === 'UPDATE') {
      if (item.oldVal && item.newVal) {
        return `alterou ${field} de "${item.oldVal}" para "${item.newVal}"`;
      }
      return `atualizou ${field}`;
    }
    if (item.actionType === 'DELETE') return `removeu ${field}`;
    return item.actionType.toLowerCase();
  }
</script>

<div class="overflow-hidden rounded-sm" style="border: 1px solid var(--app-border-faint, rgba(255, 255, 255, 0.05));">
  <button
    type="button"
    onclick={() => (isOpen = !isOpen)}
    class="group flex w-full items-center justify-between px-4 py-3 transition-colors hover:bg-white/5"
    style="background: var(--app-hover, rgba(255, 255, 255, 0.03));"
  >
    <div class="flex items-center gap-2.5">
      <Clock class="h-3.5 w-3.5" style="color: var(--app-text-muted);" />
      <span class="text-[13px] font-semibold" style="color: var(--app-text-muted);">
        Edit History
      </span>
      {#if history.length > 0}
        <span
          class="rounded-sm px-1.5 py-0.5 text-[10px] font-bold"
          style="background: var(--app-border, rgba(255, 255, 255, 0.1)); color: var(--app-text-muted);"
        >
          {history.length}
        </span>
      {/if}
    </div>
    <ChevronDown
      class="h-4 w-4 transition-transform duration-200 {isOpen ? 'rotate-180' : ''}"
      style="color: var(--app-text-muted);"
    />
  </button>

  {#if isOpen}
    <div
      class="px-4 pt-3 pb-4"
      style="border-top: 1px solid var(--app-border-faint, rgba(255, 255, 255, 0.05));"
    >
      {#if sortedHistory.length === 0}
        <p class="py-3 text-center text-[12px] italic" style="color: var(--app-text-muted);">
          No edit history recorded.
        </p>
      {:else}
        <ol class="relative mt-1 space-y-3 pl-6">
          <div
            class="absolute top-2 bottom-2 left-2 w-px"
            style="background: var(--app-border, rgba(255, 255, 255, 0.1));"
          ></div>
          {#each sortedHistory as item (item.id)}
            {@const author = getUser(item.createdBy) || (item.author ? { username: item.author.username, avatarUrl: item.author.avatarUrl || undefined, displayName: item.author.username } : undefined)}
            <li class="relative">
              <span
                class="absolute -left-5.5 top-1.5 h-2 w-2 rounded-full"
                style="background: var(--app-primary, #818cf8); box-shadow: 0 0 0 2px var(--app-panel, #212124);"
              ></span>
              <div class="flex items-start gap-2">
                {#if author}
                  <img
                    src={author.avatarUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${author.username}`}
                    alt=""
                    class="h-4 w-4 rounded-xs object-cover"
                  />
                {/if}
                <div class="min-w-0 flex-1 text-xs">
                  <span class="font-bold text-white/90">
                    {author?.displayName || author?.username || 'Sistema'}
                  </span>&nbsp;
                  <span class="text-white/60">{formatAction(item)}</span>
                  <span class="ml-2 text-[10px] text-white/30">
                    {formatTimeAgo(item.createdAt)}
                  </span>
                </div>
              </div>
            </li>
          {/each}
        </ol>
      {/if}
    </div>
  {/if}
</div>
