// src/modules/card/components/CardPriority.tsx
const PRIORITY_STYLES: Record<string, { color: string; label: string }> = {
  high: { color: "#f87171", label: "High" },
  medium: { color: "#fbbf24", label: "Medium" },
  low: { color: "#34d399", label: "Low" },
};

export function CardPriority({ priority }: { priority: string }) {
  const key = priority?.toLowerCase();
  const style = PRIORITY_STYLES[key as keyof typeof PRIORITY_STYLES];

  const color = style?.color || "rgba(156, 163, 175, 0.8)";
  const label = style?.label || priority;

  return (
    <span
      className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md"
      style={{
        color: color,
        background: `${color}${color.startsWith('#') ? '18' : ''}`,
        border: `1px solid ${color}40`
      }}
    >
      <span className="w-1.5 h-1.5 rounded-full" style={{ background: color }} />
      {label}
    </span>
  );
}

// src/lib/components/card/CardPriority.svelte
<script lang="ts">
  interface Props {
    priority: string | { name: string; color?: string; icon?: string };
  }

  let { priority }: Props = $props();

  const PRIORITY_STYLES: Record<string, { color: string; label: string }> = {
    high: { color: 'var(--priority-high, #f87171)', label: 'High' },
    medium: { color: 'var(--priority-medium, #fbbf24)', label: 'Medium' },
    low: { color: 'var(--priority-low, #34d399)', label: 'Low' },
  };

  const style = $derived.by(() => {
    if (typeof priority === 'object') {
      return {
        color: priority.color || 'var(--priority-medium, #fbbf24)',
        label: priority.name,
      };
    }
    const key = priority.toLowerCase();
    return PRIORITY_STYLES[key] || { color: 'rgba(156, 163, 175, 0.8)', label: priority };
  });
</script>

<span
  class="flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[10px] font-bold tracking-wider uppercase"
  style="
    color: {style.color};
    background: {style.color.startsWith('#') ? `${style.color}18` : 'rgba(255, 255, 255, 0.05)'};
    border: 1px solid {style.color.startsWith('#') ? `${style.color}40` : 'rgba(255, 255, 255, 0.1)'};
  "
>
  <span class="h-1.5 w-1.5 rounded-full" style="background: {style.color};"></span>
  {style.label}
</span>
