// src/lib/components/card-modal/pickers/PriorityPicker.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Flag, Check, Plus, Loader2 } from 'lucide-svelte';
  import type { PriorityModel } from '$lib/contracts/models';

  interface Props {
    selectedPriorityId?: string | null;
    priorities?: PriorityModel[];
    workspaceId: string;
    onselect?: (priorityId: string) => void;
  }

  let {
    selectedPriorityId = null,
    priorities = [],
    workspaceId,
    onselect,
  }: Props = $props();

  let isOpen = $state(false);
  let containerEl = $state<HTMLDivElement | null>(null);
  let newPrioName = $state('');
  let isCreating = $state(false);

  const selectedPriority = $derived(priorities.find((p) => p.id === selectedPriorityId));

  const COLORS = ['#f87171', '#fbbf24', '#34d399', '#818cf8', '#c084fc'];
  const ICONS = ['↑', '→', '↓', '!', '★'];

  async function handleCreate() {
    const trimmed = newPrioName.trim();
    if (!trimmed) return;
    isCreating = true;
    const color = COLORS[Math.floor(Math.random() * COLORS.length)];
    const icon = ICONS[Math.floor(Math.random() * ICONS.length)];
    try {
      const res = await fetch(`/api/workspaces/${workspaceId}/priorities`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: trimmed, color, icon }),
      });
      if (res.ok) {
        const created = await res.json();
        priorities.push(created);
        onselect?.(created.id);
        newPrioName = '';
      }
    } catch {
      // Ignorar erro
    } finally {
      isCreating = false;
    }
  }

  onMount(() => {
    function handleClickOutside(event: MouseEvent) {
      if (containerEl && !containerEl.contains(event.target as Node)) {
        isOpen = false;
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div bind:this={containerEl} class="relative">
  <button
    type="button"
    onclick={() => (isOpen = !isOpen)}
    aria-label="Prioridade"
    class="flex h-9 w-9 items-center justify-center rounded-sm transition-all"
    style="
      background: {isOpen ? 'var(--app-border, rgba(255, 255, 255, 0.1))' : 'var(--app-hover, rgba(255, 255, 255, 0.05))'};
      border: 1px solid var(--app-border, rgba(255, 255, 255, 0.1));
      color: {selectedPriority?.color || 'var(--app-text-muted)'};
    "
    title="Prioridade"
  >
    <Flag class="h-4 w-4" />
  </button>

  {#if isOpen}
    <div
      class="absolute top-11 right-0 z-50 w-56 p-1.5 shadow-2xl"
      style="
        border-radius: 6px;
        background: var(--app-panel, #212124);
        border: 1px solid var(--app-border, rgba(255, 255, 255, 0.1));
        box-shadow: 0 16px 48px rgba(0, 0, 0, 0.4);
      "
    >
      <div class="mb-1.5 px-2 py-1 text-[10px] font-bold tracking-wider text-[var(--app-text-muted)] uppercase">
        Priority
      </div>

      <div class="max-h-48 space-y-0.5 overflow-y-auto">
        {#each priorities as prio (prio.id)}
          {@const isSelected = prio.id === selectedPriorityId}
          <button
            type="button"
            onclick={() => {
              onselect?.(prio.id);
              isOpen = false;
            }}
            class="flex w-full items-center justify-between rounded-sm px-2.5 py-1.5 text-left text-[12px] font-medium transition-colors hover:bg-white/5"
            style="color: {prio.color || 'var(--app-text)'};"
          >
            <div class="flex items-center gap-2">
              <span>{prio.icon}</span>
              <span>{prio.name}</span>
            </div>
            {#if isSelected}
              <Check class="h-3.5 w-3.5 text-indigo-400" />
            {/if}
          </button>
        {/each}
      </div>

      <div class="mt-2 border-t border-white/5 pt-2">
        <div class="flex items-center gap-1.5">
          <input
            type="text"
            placeholder="New priority..."
            bind:value={newPrioName}
            onkeydown={(e) => {
              if (e.key === 'Enter') handleCreate();
            }}
            class="w-full rounded-sm border border-[var(--app-border)] bg-[var(--app-bg)] px-2 py-1 text-[11px] text-[var(--app-text)] focus:border-indigo-500 focus:outline-none"
          />
          <button
            type="button"
            onclick={handleCreate}
            disabled={isCreating}
            aria-label="Add priority"
            class="flex h-6 w-6 shrink-0 items-center justify-center rounded-sm bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50"
          >
            {#if isCreating}
              <Loader2 class="h-3 w-3 animate-spin" />
            {:else}
              <Plus class="h-3 w-3" />
            {/if}
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>

// src/modules/card/components/card-modal/pickers/PriorityPicker.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Flag, Check, Plus, Trash2, Loader2 } from "lucide-react";
import { createPriorityAction, deletePriorityAction } from "@/modules/workspace/actions/settings";

interface PriorityPickerProps {
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
  selectedPriority: string | null;
  onSelect: (priorityId: string) => void;
  priorities: any[];
  workspaceId: string;
}

const COLORS = ["#f87171", "#fbbf24", "#34d399", "#818cf8", "#c084fc"];
const ICONS = ["↑", "→", "↓", "!", "★"];

export function PriorityPicker({ isOpen, setIsOpen, selectedPriority, onSelect, priorities, workspaceId }: PriorityPickerProps) {
  const [newPrioName, setNewPrioName] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const currentPriorityData = priorities.find((p) => p.name === selectedPriority);

  const handleCreate = async () => {
    if (!newPrioName.trim()) return;
    setIsCreating(true);
    const color = COLORS[Math.floor(Math.random() * COLORS.length)];
    const icon = ICONS[Math.floor(Math.random() * ICONS.length)];
    try {
      await createPriorityAction(workspaceId, newPrioName.trim(), color, icon);
      setNewPrioName("");
    } catch (err) {
      console.error(err);
    } finally {
      setIsCreating(false);
    }
  };

  const handleDelete = async (e: React.MouseEvent, prioId: string) => {
    e.stopPropagation();
    try {
      await deletePriorityAction(workspaceId, prioId);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-center w-9 h-9 rounded-sm transition-all"
        style={{
          background: isOpen ? "var(--app-border)" : "var(--app-hover)",
          border: "1px solid var(--app-border)",
          color: currentPriorityData?.color || "var(--app-text-muted)",
        }}
        title="Prioridade"
      >
        <Flag className="w-4 h-4" />
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 6, scale: 0.97 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 4, scale: 0.97 }}
            transition={{ type: "spring", damping: 28, stiffness: 340 }}
            className="absolute top-11 right-0 w-56 p-1.5 z-50 flex flex-col gap-1.5"
            style={{
              borderRadius: "6px",
              background: "var(--app-panel)",
              border: "1px solid var(--app-border)",
              boxShadow: "0 16px 48px rgba(0,0,0,0.4)",
            }}
          >
            <div className="max-h-48 overflow-y-auto space-y-0.5">
              {priorities.map((p) => (
                <div
                  key={p.id}
                  onClick={() => {
                    onSelect(p.name);
                    setIsOpen(false);
                  }}
                  className="group flex items-center gap-2 px-3 py-2 rounded-sm cursor-pointer transition-colors"
                  style={{
                    color: selectedPriority === p.name ? p.color : "var(--app-text-muted)",
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = "var(--app-hover)")}
                  onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
                >
                  <span className="text-sm shrink-0 w-4">{p.icon}</span>
                  <span className="flex-1 text-[13px]">{p.name}</span>
                  <div className="flex items-center gap-1">
                    {selectedPriority === p.name && <Check className="w-3.5 h-3.5" />}
                    <button
                      onClick={(e) => handleDelete(e, p.id)}
                      className="opacity-0 group-hover:opacity-100 p-1 hover:bg-red-400/10 hover:text-red-400 rounded-md transition-all"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                </div>
              ))}
              {priorities.length === 0 && (
                <div className="px-3 py-4 text-center">
                   <p className="text-[11px]" style={{ color: "var(--app-text-muted)" }}>
                     Sem prioridades configuradas
                   </p>
                </div>
              )}
            </div>

            <div className="pt-2 px-1 pb-1" style={{ borderTop: "1px solid var(--app-border-faint)" }}>
               <div className="flex items-center gap-2 px-2.5 py-2 rounded-sm border transition-all duration-200 focus-within:ring-2 focus-within:ring-[var(--app-primary)]/20"
                    style={{ 
                      background: "var(--app-bg)",
                      borderColor: "var(--app-border)",
                    }}
               >
                  <span className="text-xs w-4 text-center shrink-0" style={{ color: COLORS[0] }}>{ICONS[0]}</span>
                  <input 
                    type="text"
                    placeholder="Nova prioridade..."
                    className="flex-1 min-w-0 bg-transparent border-none text-[13px] text-[var(--app-text)] placeholder:text-[var(--app-text-muted)] focus:outline-none"
                    value={newPrioName}
                    onChange={(e) => setNewPrioName(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && handleCreate()}
                  />
                  <button 
                    onClick={handleCreate}
                    disabled={isCreating || !newPrioName.trim()}
                    className="flex items-center justify-center w-7 h-7 rounded-sm shrink-0 hover:bg-[var(--app-hover)] text-[var(--app-primary)] disabled:opacity-30 disabled:grayscale transition-all"
                  >
                    {isCreating ? <Loader2 className="w-3.5 h-3.5 animate-spin"/> : <Plus className="w-4 h-4" />}
                  </button>
               </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
