// src/lib/components/ProfileModal.svelte
<script lang="ts">
  import { X, Camera, Loader2, Check, AlertCircle } from 'lucide-svelte';
  import Button from '$lib/ui/Button.svelte';
  import Input from '$lib/ui/Input.svelte';
  import type { UserModel } from '$lib/contracts/models';

  interface Props {
    isOpen?: boolean;
    profile?: UserModel;
    onClose?: () => void;
    onProfileUpdated?: (updated: UserModel) => void;
  }

  let {
    isOpen = false,
    profile = { id: '', username: 'User' },
    onClose,
    onProfileUpdated,
  }: Props = $props();

  let firstName = $state('');
  let lastName = $state('');
  let email = $state('');
  let bio = $state('');
  let avatarUrl = $state('');
  let avatarPreview = $state('');

  let uploadingAvatar = $state(false);
  let saving = $state(false);
  let saved = $state(false);
  let error = $state('');

  $effect(() => {
    if (profile) {
      firstName = profile.firstName || '';
      lastName = profile.lastName || '';
      email = profile.email || '';
      bio = profile.bio || '';
      avatarUrl = profile.avatarUrl || '';
      avatarPreview = profile.avatarUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${profile.username}`;
    }
  });

  async function handleAvatarSelect(e: Event) {
    const input = e.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    if (!['image/jpeg', 'image/png', 'image/webp', 'image/gif'].includes(file.type)) {
      error = 'Please select a valid image file (JPEG, PNG, WebP, GIF).';
      return;
    }

    if (file.size > 10 * 1024 * 1024) {
      error = 'Image must be smaller than 10 MiB.';
      return;
    }

    uploadingAvatar = true;
    error = '';

    try {
      const formData = new FormData();
      formData.append('file', file);

      const res = await fetch('/api/files/avatar', {
        method: 'POST',
        body: formData,
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || 'Failed to upload avatar.');
      }

      const data = await res.json();
      avatarUrl = data.url;
      avatarPreview = data.url;
    } catch (err: unknown) {
      error = err instanceof Error ? err.message : 'Error uploading avatar.';
    } finally {
      uploadingAvatar = false;
    }
  }

  async function handleSubmit(e: Event) {
    e.preventDefault();
    saving = true;
    saved = false;
    error = '';

    try {
      const res = await fetch('/api/users/me', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          first_name: firstName.trim() || undefined,
          last_name: lastName.trim() || undefined,
          email: email.trim() || undefined,
          bio: bio.trim() || undefined,
          avatar_url: avatarUrl || undefined,
        }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || 'Failed to update profile.');
      }

      const updated = await res.json();
      saved = true;
      onProfileUpdated?.(updated);
      setTimeout(() => {
        saved = false;
        onClose?.();
      }, 1000);
    } catch (err: unknown) {
      error = err instanceof Error ? err.message : 'Failed to update profile.';
    } finally {
      saving = false;
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose?.();
  }
</script>

<svelte:window onkeydown={handleKeyDown} />

{#if isOpen}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
    role="dialog"
    aria-modal="true"
    aria-labelledby="profile-modal-title"
  >
    <div
      class="bg-app-bg border-app-border flex w-full max-w-[460px] flex-col overflow-hidden rounded-sm border shadow-[0_32px_80px_rgba(0,0,0,0.6)]"
    >
      <div class="border-app-border-faint flex items-center justify-between border-b px-6 pt-6 pb-5">
        <h2 id="profile-modal-title" class="text-app-text text-base font-bold tracking-tight">
          Edit Profile
        </h2>
        <button
          type="button"
          onclick={onClose}
          aria-label="Close modal"
          class="text-app-text-muted hover:text-app-text hover:bg-app-panel rounded-sm p-1.5 transition-colors"
        >
          <X class="h-5 w-5" />
        </button>
      </div>

      <form onsubmit={handleSubmit} class="space-y-5 px-6 pt-5 pb-6">
        {#if error}
          <div class="flex items-start gap-2 rounded-sm border border-red-500/20 bg-red-500/10 p-3.5 text-[13px] font-medium text-red-400">
            <AlertCircle class="mt-0.5 h-4 w-4 shrink-0" />
            <span>{error}</span>
          </div>
        {/if}

        <!-- Avatar upload section -->
        <div class="flex items-center gap-4">
          <label class="group relative flex h-16 w-16 cursor-pointer items-center justify-center overflow-hidden rounded-full border border-white/10 transition-transform hover:scale-105">
            <img
              src={avatarPreview}
              alt="Avatar preview"
              class="h-full w-full object-cover"
            />
            <div class="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 transition-opacity group-hover:opacity-100">
              {#if uploadingAvatar}
                <Loader2 class="h-5 w-5 animate-spin text-white" />
              {:else}
                <Camera class="h-5 w-5 text-white" />
              {/if}
            </div>
            <input
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              onchange={handleAvatarSelect}
              disabled={uploadingAvatar}
              class="hidden"
            />
          </label>
          <div>
            <p class="text-app-text text-sm font-semibold">Profile Photo</p>
            <p class="text-app-text-muted text-xs">JPEG, PNG, WebP or GIF up to 10 MiB</p>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <Input
            label="First Name"
            bind:value={firstName}
            placeholder="John"
          />
          <Input
            label="Last Name"
            bind:value={lastName}
            placeholder="Doe"
          />
        </div>

        <Input
          label="Username"
          value={profile.username}
          disabled
          hint="Username cannot be changed."
        />

        <Input
          label="Email"
          type="email"
          bind:value={email}
          placeholder="you@example.com"
          autocomplete="email"
        />

        <div class="flex flex-col space-y-1.5">
          <div class="flex items-center justify-between">
            <label for="profile-bio-input" class="text-app-text text-xs font-semibold">Bio</label>
            <span class="text-app-text-muted text-[11px]">{bio.length}/200</span>
          </div>
          <textarea
            id="profile-bio-input"
            bind:value={bio}
            maxlength={200}
            rows={3}
            placeholder="Tell us about yourself..."
            class="bg-app-bg border-app-border text-app-text focus:border-app-primary w-full resize-none rounded-sm border p-2.5 text-sm transition-colors focus:outline-none"
          ></textarea>
        </div>

        <div class="flex items-center justify-end gap-3 pt-2">
          <Button
            type="button"
            variant="ghost"
            onclick={onClose}
          >
            Cancel
          </Button>
          <Button
            type="submit"
            variant="primary"
            loading={saving}
            disabled={saving || uploadingAvatar}
          >
            {#if saved}
              <Check class="mr-1 h-4 w-4" /> Saved!
            {:else}
              Save Changes
            {/if}
          </Button>
        </div>
      </form>
    </div>
  </div>
{/if}

// src/components/ProfileModal.tsx
'use client';

import { useState } from 'react';
import { updateUserProfile } from '@/actions/user';
import { X, UserRound, Link2, Check, Camera } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ProfileModalProps {
  isOpen: boolean;
  onClose: () => void;
  profile: any;
  onProfileUpdated: (p: any) => void;
}

export default function ProfileModal({ isOpen, onClose, profile, onProfileUpdated }: ProfileModalProps) {
  const [displayName, setDisplayName] = useState(profile?.display_name || '');
  const [avatarUrl, setAvatarUrl] = useState(profile?.avatar_url || '');
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  if (!isOpen) return null;

  const resolvedAvatar = avatarUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${profile?.username}`;

  const handleSave = async () => {
    setSaving(true);
    await updateUserProfile({ display_name: displayName, avatar_url: avatarUrl });
    onProfileUpdated({ ...profile, display_name: displayName, avatar_url: avatarUrl });
    setSaving(false);
    setSaved(true);
    setTimeout(() => { setSaved(false); onClose(); }, 800);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          onClick={onClose}
          className="absolute inset-0"
          style={{ background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(14px)' }}
        />

        {/* Modal */}
        <motion.div
          initial={{ opacity: 0, y: 24, scale: 0.97 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 16, scale: 0.97 }}
          transition={{ type: 'spring', damping: 28, stiffness: 320 }}
          className="relative w-full max-w-[380px] z-10 flex flex-col overflow-hidden"
          style={{
            borderRadius: '22px',
            background: '#151515',
            border: '1px solid rgba(255,255,255,0.07)',
            boxShadow: '0 28px 72px rgba(0,0,0,0.55), 0 0 0 1px rgba(255,255,255,0.04) inset',
          }}
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 pt-5 pb-4"
            style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center"
                style={{ background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.25)' }}>
                <UserRound className="w-3.5 h-3.5 text-indigo-400" />
              </div>
              <h2 className="text-[15px] font-semibold text-white/90">Edit Profile</h2>
            </div>
            <button
              onClick={onClose}
              className="w-7 h-7 flex items-center justify-center rounded-lg text-white/30 hover:text-white/70 transition-colors"
              style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.07)' }}
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Avatar section */}
          <div className="flex flex-col items-center pt-6 pb-5 px-6">
            <div className="relative group mb-1">
              <div className="w-20 h-20 rounded-full overflow-hidden"
                style={{ border: '2px solid rgba(255,255,255,0.1)', boxShadow: '0 0 0 4px rgba(99,102,241,0.1)' }}>
                <img
                  src={resolvedAvatar}
                  alt="Avatar"
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="absolute inset-0 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                style={{ background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(4px)' }}>
                <Camera className="w-4 h-4 text-white/80" />
              </div>
            </div>
            <p className="text-[13px] text-white/30 mt-2">
              {profile?.username && <span className="text-white/40 font-medium">@{profile.username}</span>}
            </p>
          </div>

          {/* Fields */}
          <div className="px-6 pb-6 space-y-4">
            {/* Display Name */}
            <div>
              <label className="block text-[11px] font-semibold tracking-wider uppercase text-white/30 mb-2">
                Display Name
              </label>
              <input
                value={displayName}
                onChange={e => setDisplayName(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') handleSave(); }}
                className="w-full text-[14px] text-white/85 rounded-xl px-4 py-2.5 focus:outline-none transition-all placeholder-white/20"
                style={{
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.09)',
                }}
                placeholder="Your full name"
              />
            </div>

            {/* Avatar URL */}
            <div>
              <label className="block text-[11px] font-semibold tracking-wider uppercase text-white/30 mb-2">
                Avatar URL
              </label>
              <div className="relative">
                <Link2 className="absolute left-3.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-white/25 pointer-events-none" />
                <input
                  value={avatarUrl}
                  onChange={e => setAvatarUrl(e.target.value)}
                  className="w-full text-[14px] text-white/85 rounded-xl pl-9 pr-4 py-2.5 focus:outline-none transition-all placeholder-white/20"
                  style={{
                    background: 'rgba(255,255,255,0.04)',
                    border: '1px solid rgba(255,255,255,0.09)',
                  }}
                  placeholder="https://example.com/avatar.png"
                />
              </div>
            </div>

            {/* Save button */}
            <motion.button
              onClick={handleSave}
              disabled={saving || saved}
              whileTap={{ scale: 0.97 }}
              className="w-full mt-1 py-2.5 rounded-xl text-sm font-semibold transition-all flex items-center justify-center gap-2"
              style={{
                background: saved ? 'rgba(16,185,129,0.1)' : 'rgba(255,255,255,0.05)',
                border: `1px solid ${saved ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.1)'}`,
                color: saved ? '#34d399' : '#fff',
                opacity: saving ? 0.6 : 1,
              }}
            >
              <AnimatePresence mode="wait">
                {saved ? (
                  <motion.span key="saved" initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} className="flex items-center gap-1.5">
                    <Check className="w-4 h-4" /> Saved!
                  </motion.span>
                ) : saving ? (
                  <motion.span key="saving" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                    Saving...
                  </motion.span>
                ) : (
                  <motion.span key="idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                    Save Profile
                  </motion.span>
                )}
              </AnimatePresence>
            </motion.button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
