// src/lib/components/card-modal/DescriptionTab.svelte
<script lang="ts">
  import SanitizedMarkdown from '$lib/ui/SanitizedMarkdown.svelte';
  import { attachmentMarkdown } from '$lib/utils/attachments';
  import AttachmentCard from './AttachmentCard.svelte';
  import HistorySection from './HistorySection.svelte';
  import type { AttachmentModel, IssueEventModel, UserModel } from '$lib/contracts/models';

  interface Props {
    description?: string;
    isEditing?: boolean;
    savedStatus?: 'idle' | 'saving' | 'saved';
    history?: IssueEventModel[];
    allUsers?: UserModel[];
    workspaceId: string;
    onupdatedescription?: (desc: string) => void;
  }

  let {
    description = '',
    isEditing = $bindable(false),
    savedStatus = 'idle',
    history = [],
    allUsers = [],
    workspaceId,
    onupdatedescription,
  }: Props = $props();

  let localDesc = $derived(description);
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let deletingUrl = $state<string | null>(null);

  const attachments = $derived.by(() => {
    const values: AttachmentModel[] = [];
    const regex = /!\[([^\]]*)\]\((https?:\/\/[^\s)]+)(?:\s+["']([^"']+)["'])?\)/g;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(description)) !== null) {
      if (match[2] && match[3]) values.push({ name: match[1], url: match[2], publicId: match[3] });
    }
    return values;
  });

  function handleInput(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    localDesc = target.value;
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      onupdatedescription?.(localDesc);
    }, 1500);
  }

  function handleChecklistClick(e: MouseEvent) {
    const target = e.target as HTMLElement;
    if (target.tagName === 'INPUT' && target.getAttribute('type') === 'checkbox') {
      const container = target.closest('.description-preview');
      if (!container) return;
      const checkboxes = Array.from(container.querySelectorAll('input[type="checkbox"]'));
      const index = checkboxes.indexOf(target as HTMLInputElement);
      if (index !== -1) {
        toggleChecklistIndex(index, (target as HTMLInputElement).checked);
      }
    }
  }

  function toggleChecklistIndex(targetIndex: number, checked: boolean) {
    let count = 0;
    const lines = description.split('\n');
    const newLines = lines.map((line) => {
      const match = line.match(/^([\s]*[-*+]\s+\[)[ xX](\].*)/i);
      if (match) {
        if (count === targetIndex) {
          count++;
          return `${match[1]}${checked ? 'x' : ' '}${match[2]}`;
        }
        count++;
      }
      return line;
    });
    const updated = newLines.join('\n');
    onupdatedescription?.(updated);
  }

  async function handleDeleteAttachment(attachment: AttachmentModel) {
    deletingUrl = attachment.url;
    try {
      // The public ID comes from the upload response and is persisted in the image title.
      const response = await fetch('/api/files/attachments', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ workspace_id: workspaceId, key: attachment.publicId }),
      });
      if (!response.ok) throw new Error('Falha ao excluir anexo.');
      const cleanDesc = description.replace(attachmentMarkdown(attachment), '').trim();
      onupdatedescription?.(cleanDesc);
    } catch {
      // Falha silenciosa de deleção remota
    } finally {
      deletingUrl = null;
    }
  }
</script>

<div class="space-y-4">
  {#if isEditing}
    <div class="relative z-20 space-y-3">
      <textarea
        value={localDesc}
        oninput={handleInput}
        rows={8}
        placeholder="Adicione uma descrição mais detalhada em Markdown..."
        class="w-full resize-y rounded-sm border border-[var(--app-primary)] bg-[var(--app-panel)] p-3.5 font-mono text-[13px] leading-relaxed text-[var(--app-text)] focus:outline-none"
      ></textarea>

      <div class="flex items-center justify-between">
        <span class="px-1 text-[11px] font-bold tracking-widest uppercase opacity-50">
          {#if savedStatus === 'saving'}
            <span class="animate-pulse" style="color: var(--color-warning, #fbbf24);">
              Saving
            </span>
          {:else if savedStatus === 'saved'}
            <span style="color: var(--color-success, #34d399);">✓ Saved</span>
          {:else}
            <span>Markdown · Auto-save</span>
          {/if}
        </span>
        <button
          type="button"
          onclick={() => {
            if (debounceTimer) clearTimeout(debounceTimer);
            onupdatedescription?.(localDesc);
            isEditing = false;
          }}
          class="text-app-text-muted hover:text-app-text hover:bg-app-panel rounded-sm px-3 py-1 text-[12px] font-bold tracking-wider uppercase transition-all"
        >
          Close editor
        </button>
      </div>
    </div>
  {:else}
    <div
      role="button"
      tabindex="0"
      onclick={() => (isEditing = true)}
      onkeydown={(e) => {
        if (e.key === 'Enter') isEditing = true;
      }}
      class="group cursor-text rounded-sm p-4 transition-all"
      style="border: 1px dashed var(--app-border, rgba(255, 255, 255, 0.15));"
    >
      {#if description.trim()}
        <!-- Intercept checklist clicks -->
        <div
          class="description-preview prose-content"
          role="presentation"
          onclick={handleChecklistClick}
        >
          <SanitizedMarkdown markdown={description} />
        </div>
      {:else}
        <p class="text-sm italic" style="color: var(--app-text-muted); opacity: 0.5;">
          Click to add a detailed description (Markdown supported)...
        </p>
      {/if}
    </div>
  {/if}

  <!-- Attachments section -->
  {#if attachments.length > 0}
    <div class="space-y-2 pt-2">
      <h3 class="text-[11px] font-bold tracking-wider text-[var(--app-text-muted)] uppercase">
        Anexos ({attachments.length})
      </h3>
      <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
        {#each attachments as attachment (attachment.publicId)}
          <AttachmentCard
            url={attachment.url}
            publicId={attachment.publicId}
            name={attachment.name}
            isDeleting={deletingUrl === attachment.url}
            ondelete={() => handleDeleteAttachment(attachment)}
          />
        {/each}
      </div>
    </div>
  {/if}

  <!-- History Section -->
  <div class="pt-2">
    <HistorySection {history} {allUsers} />
  </div>
</div>

// src/modules/card/components/card-modal/description-tab/DescriptionTab.tsx
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { DescriptionEditor } from "./DescriptionEditor";
import { HistorySection } from "./HistorySection";
import { AttachmentCard } from "../AttachmentCard";
import { extractStorageUrls, isImageUrl } from "@/modules/shared/utils/attachments";
import { deleteFileAction } from "@/modules/shared/actions/upload";

interface DescriptionTabProps {
  description: string;
  setDescription: (val: string) => void;
  isEditing: boolean;
  setIsEditing: (val: boolean) => void;
  savedStatus: "idle" | "saving" | "saved";
  history: any[];
  allUsers: any[];
  workspaceId: string;
}

export function DescriptionTab({
  description,
  setDescription,
  isEditing,
  setIsEditing,
  savedStatus,
  history,
  allUsers,
  workspaceId,
}: DescriptionTabProps) {
  const urls = extractStorageUrls(description);
  const attachments = urls.filter(url => !isImageUrl(url));

  const handleChecklistToggle = (targetIndex: number, checked: boolean) => {
    let count = 0;
    const lines = description.split("\n");
    const newLines = lines.map((line) => {
      const match = line.match(/^([\s]*[-*+]\s+\[)[ xX](\].*)/i);
      if (match) {
        if (count === targetIndex) {
          count++;
          return `${match[1]}${checked ? "x" : " "}${match[2]}`;
        }
        count++;
      }
      return line;
    });
    setDescription(newLines.join("\n"));
  };

  const handleDeleteAttachment = async (url: string) => {
    // 1. Remover do texto (Markdown)
    const newDescription = description.replace(new RegExp(`\\[.*?\\]\\(${url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\)`, 'g'), '');
    const finalDescription = newDescription.replace(new RegExp(`!?\\[.*?\\]\\(${url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\)`, 'g'), '').trim();
    setDescription(finalDescription);

    // 2. Apagar do bucket — fire-and-forget com log de erro para não bloquear a UI
    deleteFileAction(workspaceId, url).catch(console.error);
  };
  return (
    <div className="space-y-4">
      {isEditing ? (
        <div className="space-y-3 relative z-20">
          <DescriptionEditor
            value={description}
            onChange={setDescription}
            savedStatus={savedStatus}
            onClose={() => setIsEditing(false)}
            workspaceId={workspaceId}
          />
        </div>
      ) : (
        <div
          onClick={() => setIsEditing(true)}
          className="group cursor-text rounded-sm p-4 transition-all"
          style={{ border: "1px dashed var(--app-border)" }}
          onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--app-primary)")}
          onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--app-border)")}
        >
          {description ? (
            <div
              className="prose prose-invert prose-sm max-w-none"
              style={{ color: "var(--app-text-muted)" }}
            >
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  img: ({ src, alt }) => (
                    <img
                      src={src}
                      alt={alt}
                      className="rounded-sm max-w-full h-auto my-2"
                      style={{ border: "1px solid var(--app-border-faint)" }}
                    />
                  ),
                  a: ({ href, children }) => (
                    <a
                      href={href}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{ color: "var(--app-primary)" }}
                    >
                      {children}
                    </a>
                  ),
                  input: ({ checked, ...props }) => {
                    if (props.type === "checkbox") {
                      // We need a stable way to find the index.
                      // Since we are in a functional render, we can't easily use a counter 
                      // if the component tree is complex, but for a simple list it works.
                      // However, ReactMarkdown might call this in ways that break a simple counter.
                      // Let's use a trick: the 'index' is hidden in the parent's children or similar.
                      // Actually, a simpler way is to just let the user edit the text if they want 
                      // precision, but for the 'interactive' feel, we'll use a hacky counter 
                      // that resets via a unique prop if needed.
                      return (
                        <input
                          {...props}
                          type="checkbox"
                          checked={checked}
                          onChange={(e) => {
                            // We'll calculate the index by finding all inputs in the parent container
                            const inputs = Array.from(e.target.closest('.prose')?.querySelectorAll('input[type="checkbox"]') || []);
                            const idx = inputs.indexOf(e.target as HTMLInputElement);
                            if (idx !== -1) {
                              handleChecklistToggle(idx, e.target.checked);
                            }
                          }}
                          onClick={(e) => e.stopPropagation()}
                          className="mr-2 cursor-pointer accent-[var(--app-primary)] w-3.5 h-3.5 mt-1 !opacity-100 !pointer-events-auto"
                        />
                      );
                    }
                    return <input {...props} />;
                  },
                }}
              >
                {description}
              </ReactMarkdown>
            </div>
          ) : (
            <p
              className="text-sm italic opacity-40"
              style={{ color: "var(--app-text)" }}
            >
              Add a description… Supports **Markdown**.
            </p>
          )}
          <p
            className="mt-3 text-xs font-medium opacity-0 group-hover:opacity-100 transition-opacity"
            style={{ color: "var(--app-primary)" }}
          >
            Click to edit
          </p>
        </div>
      )}

      {/* Description Attachments Section */}
      {!isEditing && attachments.length > 0 && (
        <div className="space-y-2 pt-2">
          <h4 className="text-[10px] font-bold uppercase tracking-widest opacity-40 px-1">Attachments</h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {attachments.map((url, i) => (
              <AttachmentCard 
                key={i} 
                url={url} 
                onDelete={() => handleDeleteAttachment(url)} 
              />
            ))}
          </div>
        </div>
      )}

      <HistorySection history={history} allUsers={allUsers} />
    </div>
  );
}
