// src/lib/components/card-modal/CommentsTab.svelte
<script lang="ts">
  import { MessageSquare } from 'lucide-svelte';
  import CommentInput from './CommentInput.svelte';
  import CommentItem from './CommentItem.svelte';
  import type { CommentModel, UserModel } from '$lib/contracts/models';

  interface Props {
    comments?: CommentModel[];
    loading?: boolean;
    allUsers?: UserModel[];
    currentUserId?: string;
    currentUserAvatar?: string;
    workspaceId: string;
    onpostcomment?: (text: string, parentId?: string | null) => Promise<void> | void;
    ondeletecomment?: (commentId: string) => void;
    onupdatecomment?: (commentId: string, newContent: string) => void;
  }

  let {
    comments = [],
    loading = false,
    allUsers = [],
    currentUserId,
    currentUserAvatar = '',
    workspaceId,
    onpostcomment,
    ondeletecomment,
    onupdatecomment,
  }: Props = $props();

  let replyingTo = $state<{ id: string; authorName?: string } | null>(null);

  const rootComments = $derived(comments.filter((c) => !c.parentId));

  const repliesMap = $derived.by(() => {
    const map: Record<string, CommentModel[]> = {};
    for (const c of comments) {
      if (c.parentId) {
        (map[c.parentId] ??= []).push(c);
      }
    }
    return map;
  });

  function handleReply(parent: CommentModel) {
    const author = parent.author || allUsers.find((u) => u.id === parent.createdBy);
    replyingTo = {
      id: parent.id,
      authorName: author?.displayName || author?.username,
    };
  }
</script>

<div class="space-y-6">
  <!-- Input -->
  <CommentInput
    avatarUrl={currentUserAvatar}
    {replyingTo}
    {allUsers}
    {workspaceId}
    onpost={onpostcomment}
    oncancelreply={() => (replyingTo = null)}
  />

  <!-- Comments List -->
  {#if loading}
    <div class="space-y-4">
      {#each [0, 1] as index (index)}
        <div class="flex animate-pulse gap-3">
          <div class="h-8 w-8 shrink-0 rounded-full" style="background: var(--app-border);"></div>
          <div class="flex-1 space-y-2">
            <div class="h-3 w-1/3 rounded" style="background: var(--app-border);"></div>
            <div class="h-10 rounded-sm" style="background: var(--app-border-faint);"></div>
          </div>
        </div>
      {/each}
    </div>
  {:else if comments.length === 0}
    <div class="py-8 text-center">
      <div
        class="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-sm"
        style="background: var(--app-hover); border: 1px solid var(--app-border);"
      >
        <MessageSquare class="h-5 w-5" style="color: var(--app-text-muted); opacity: 0.5;" />
      </div>
      <p class="text-sm" style="color: var(--app-text-muted); opacity: 0.6;">
        No comments yet. Be the first!
      </p>
    </div>
  {:else}
    <div class="custom-scrollbar max-h-96 space-y-4 overflow-y-auto pr-2">
      {#each rootComments as comment (comment.id)}
        <div class="space-y-2">
          <CommentItem
            {comment}
            {allUsers}
            {currentUserId}
            onreply={handleReply}
            ondelete={ondeletecomment}
            onupdate={onupdatecomment}
          />

          <!-- Nested replies -->
          {#if repliesMap[comment.id]}
            <div class="space-y-2">
              {#each repliesMap[comment.id] as reply (reply.id)}
                <CommentItem
                  comment={reply}
                  isReply={true}
                  {allUsers}
                  {currentUserId}
                  ondelete={ondeletecomment}
                  onupdate={onupdatecomment}
                />
              {/each}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

// src/modules/card/components/card-modal/comments-tab/CommentsTab.tsx
import { useState } from "react";
import { CommentInput } from "./CommentInput";
import { CommentThread } from "./CommentThread";
import { Comment } from "@/modules/board/actions/comments";
import { MessageSquare } from "lucide-react";

interface CommentsTabProps {
  comments: Comment[];
  loading: boolean;
  hasMore: boolean;
  isLoadingMore: boolean;
  onLoadMore: () => void;
  onPostComment: (text: string, parentId?: string | null) => void;
  onDeleteComment: (commentId: string) => void;
  currentUserId?: string;
  currentUserAvatar: string;
  allUsers: any[];
  workspaceId: string;
}

export function CommentsTab({
  comments,
  loading,
  hasMore,
  isLoadingMore,
  onLoadMore,
  onPostComment,
  onDeleteComment,
  currentUserId,
  currentUserAvatar,
  allUsers,
  workspaceId,
}: CommentsTabProps) {
  const [replyingTo, setReplyingTo] = useState<any | null>(null);

  const handleReply = (parent: any, targetUser: any) => {
    setReplyingTo(parent);
  };

  const handleCancelReply = () => setReplyingTo(null);

  const rootComments = comments.filter((c) => !c.parent_id);
  const repliesMap = new Map();
  comments.forEach((c) => {
    if (c.parent_id) {
      if (!repliesMap.has(c.parent_id)) repliesMap.set(c.parent_id, []);
      repliesMap.get(c.parent_id).push(c);
    }
  });

  return (
    <div className="space-y-6">
      {/* Input sempre visível, independente de ter comentários */}
      <CommentInput
        avatarUrl={currentUserAvatar}
        onPost={onPostComment}
        replyingTo={replyingTo}
        onCancelReply={handleCancelReply}
        allUsers={allUsers}
        workspaceId={workspaceId}
      />

      {/* Lista de comentários */}
      {loading ? (
        <div className="space-y-4">
          {[0, 1].map((i) => (
            <div key={i} className="flex gap-3 animate-pulse">
              <div className="w-8 h-8 rounded-sm shrink-0" style={{ background: "var(--app-border)" }} />
              <div className="flex-1 space-y-2">
                <div className="h-3 rounded" style={{ width: "30%", background: "var(--app-border)" }} />
                <div className="h-12 rounded-sm" style={{ background: "var(--app-border-faint)" }} />
              </div>
            </div>
          ))}
        </div>
      ) : comments.length === 0 ? (
        <div className="py-6 text-center">
          <div
            className="w-10 h-10 rounded-sm mx-auto mb-3 flex items-center justify-center"
            style={{ background: "var(--app-hover)", border: "1px solid var(--app-border)" }}
          >
            <MessageSquare className="w-5 h-5" style={{ color: "var(--app-text-muted)", opacity: 0.5 }} />
          </div>
          <p className="text-sm" style={{ color: "var(--app-text-muted)", opacity: 0.6 }}>
            No comments yet. Be the first!
          </p>
        </div>
      ) : (
        <div className="space-y-4 max-h-[38vh] overflow-y-auto pr-2 pb-2 custom-scrollbar" style={{ scrollbarWidth: "thin", scrollbarColor: "var(--app-border) transparent" }}>
          {rootComments.map((comment, i) => (
            <CommentThread
              key={comment.id}
              comment={comment}
              replies={repliesMap.get(comment.id) || []}
              index={i}
              onReply={handleReply}
              onDelete={onDeleteComment}
              allUsers={allUsers}
              currentUserId={currentUserId}
            />
          ))}
          {hasMore && (
            <button
              onClick={onLoadMore}
              disabled={isLoadingMore}
              className="w-full py-2 text-xs font-semibold transition-colors rounded-sm flex justify-center items-center gap-1.5 disabled:opacity-50"
              style={{ color: "var(--app-text-muted)", border: "1px solid var(--app-border-faint)" }}
              onMouseEnter={(e) => {
                e.currentTarget.style.color = "var(--app-primary)";
                e.currentTarget.style.borderColor = "var(--app-primary)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.color = "var(--app-text-muted)";
                e.currentTarget.style.borderColor = "var(--app-border-faint)";
              }}
            >
              {isLoadingMore ? "Loading…" : "Show more ⌄"}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
